#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

SECONDS=1
counter=0

rm -f agreement.log

infile="agreements.tsv"

numrecs=$(wc -l ${infile} |cut -d " " -f1)


while IFS=$'\t' read -r name package_id vendor_id;do 
	if [[ $SECONDS -gt 500 ]]; then
		auth 2>/dev/null || authn 2>/dev/null
		okapi_token=$(cat okapi.token)
		SECONDS=1
	fi

	counter=$(($counter + 1))
	echo "Processing ${name} -- record $counter of $numrecs"
	keyname=$(tr -dc [a-z0-9] <<< ${name,,})
	package_id="${vendor_id}-${package_id}"

	# agreement uuid -- needs to be global
        namespace="8405ae4d-b315-42e1-918a-d1919900cf3f"
        uuid=$(uuid -v 5  ${namespace} ${okapi_url}:agreements:${keyname})

	start_date=$(date -I)
	agreement=$(jq -n --arg START ${start_date} --arg NAME "${name}" --arg UUID ${uuid} '{"periods":[{"startDate":$START}],"name":$NAME,"agreementStatus":"active","orgs":[],"alternateNames":[],"outwardRelationships":[],"inwardRelationships":[],"linkedLicenses":[],"id":$UUID}')

	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${agreement}" "${okapi_url}/erm/sas")
	agreement_uuid=$(jq -r .id <<< ${apicall})

	echo "${apicall}" >> agreement.log
	agreement_line=$(jq -n --arg PACKAGE ${package_id} --arg AGREEMENT ${agreement_uuid} '{"type":"external","authority":"ekb-package","reference":$PACKAGE,"owner":$AGREEMENT}')
	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${agreement_line}" "${okapi_url}/erm/entitlements")
	echo "${apicall}" >> agreement.log
done < ${infile}


