#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

while read -r userBarcode itemBarcode;do 

IFS='' read -r -d '' data << EndOfJSON
{
    "userBarcode" : "${userBarcode}",
    "itemBarcode" : "${itemBarcode}",
    "servicePointId" : "7c70450a-8d49-49e8-93cd-b2e9a3f1b9bc"
  }
EndOfJSON


apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${data}" "${okapi_url}/circulation/check-out-by-barcode")

echo -e "${apicall}" |jq '.'

done < barcodes
