#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

date=$(date +"%Y-%m-%dT%H:%M:%S%:z")
infile="barcodes"
outfile="checkin.log"

numrecs=$(wc -l ${infile} |cut -d " " -f1)
counter=0

while read -r barcode;do 

IFS='' read -r -d '' data << EndOfJSON
{
    "itemBarcode" : "${barcode}",
    "checkInDate" : "${date}",
    "servicePointId" : "892f3568-ff0b-4c30-ba67-03801f5679b6"
  }
EndOfJSON


	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${data}" "${okapi_url}/circulation/check-in-by-barcode")

	counter=$(($counter + 1))

	printf "Checking in %s -- item %s of %s\r" ${barcode} $counter $numrecs
	echo -e "${barcode}	${apicall}" | tr -d '\n' |sed 's/$/\n/' >> ${outfile}

done < ${infile}

echo "Finished checking in $numrecs items."
echo "API output has been sent to ${outfile}"


