#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
okapi_url=$(cat okapi.url)
tenant=$(cat tenant)
okapi_token=$(cat okapi.token)
testKey="."

if [[ -z ${2} ]];then
	echo "Usage: circrules-test [user_barcode] [item_barcode] "
	echo
	echo "Options:"
	echo "-g Use group from loan"
	echo "-l Use location from loan"
	echo "-k [keyword] Search rule for keyword or UUID"
	echo
	echo "Note that using -g or -l options requires that the circ rule specifies the group or location in the criteria which may cause the actual rule involved not to be retrieved"
	echo
	exit
fi

while getopts "gk:l" opt; do
  case $opt in
    g)
      testGroup=1 ;;
    k)
      testKey=$OPTARG ;;
    l)
      testLocation=1 ;;
    \?) # Handle invalid options
      echo "Error: Invalid option -$OPTARG" >&2
      echo "Usage: $0 [-g] [-k keyword]" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

userId=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/users?query=barcode==${1}" |jq -r .users[0].id)
itemId=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/inventory/items?query=barcode==${2}" |jq -r .items[0].id) 


loan=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/loan-storage/loans?query=itemId==${itemId}%20and%20userId==${userId}%20sortby%20loanDate%20desc" |jq '.loans[0]')


loanPolicyId=$(jq -r .loanPolicyId <<< "${loan}")
patronGroupIdAtCheckout=$(jq -r .patronGroupIdAtCheckout <<< "${loan}")
overdueFinePolicyId=$(jq -r .overdueFinePolicyId <<< "${loan}")
lostItemPolicyId=$(jq -r .lostItemPolicyId <<< "${loan}")
locationId=$(jq -r .itemEffectiveLocationIdAtCheckOut <<< "${loan}")

curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/circulation/rules" > circrules.json  &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/loan-types?query=cql.allRecords=1&limit=1000" |jq -c .loantypes[] > loantypes.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/material-types?query=cql.allRecords=1&limit=1000" |jq -c .mtypes[] > mattypes.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/groups?query=cql.allRecords=1&limit=1000" |jq -c .usergroups[] > groups.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/loan-policy-storage/loan-policies?query=cql.allRecords=1&limit=1000" |jq -c .loanPolicies[] > loanpolicies.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/lost-item-fees-policies?query=cql.allRecords=1&limit=1000" |jq -c .lostItemFeePolicies[] > lostitempolicies.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/overdue-fines-policies?query=cql.allRecords=1&limit=1000" |jq -c .overdueFinePolicies[] > overduefinepolicies.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/patron-notice-policy-storage/patron-notice-policies?query=cql.allRecords=1&limit=1000" |jq -c .patronNoticePolicies[] > noticepolicies.json &
curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/request-policy-storage/request-policies?query=cql.allRecords=1&limit=1000" |jq -c .requestPolicies[] > requestpolicies.json &
wait

jq -r '. | "s/\(.id)/\((.group // .name)|gsub("/";"\\/"))/g"' loantypes.json mattypes.json groups.json loanpolicies.json lostitempolicies.json overduefinepolicies.json noticepolicies.json requestpolicies.json > temp.sed

jq --arg loanPolicyId "${loanPolicyId}" \
   --arg patronGroupIdAtCheckout "${patronGroupIdAtCheckout}" \
   --arg locationId "${locationId}" \
   --arg overdueFinePolicyId "${overdueFinePolicyId}" \
   --arg lostItemPolicyId "${lostItemPolicyId}" \
   --arg testLocation "${testLocation}" \
   --arg testGroup "${testGroup}" -c '
  .rulesAsText
  | gsub("\r";"")             
  | split("\n")              
  | to_entries                                      # [{key, value}, ...] where key is 0-based
  | map(select(
			(
				(($testGroup != "1")) or
      	(.value | test("\($patronGroupIdAtCheckout)")) 
			) and
			(
				(($testLocation != "1")) or
      	(.value | test("\($locationId)")) 
			) and
      (.value | test("\($loanPolicyId)")) and
      (.value | test("\($overdueFinePolicyId)")) and
      (.value | test("\($lostItemPolicyId)"))
    ))
  | map(
      (.value | capture("(?<rule>.*?)\\s*:\\s*(?<action>.*)")) as $parts
      | { line: (.key + 1), rule: $parts.rule, action: $parts.action }
    )
' circrules.json |sed -f temp.sed |jq -c .[] |grep "${testKey}" |jq -s .

rm -f temp.sed loantypes.json mattypes.json groups.json loanpolicies.json lostitempolicies.json overduefinepolicies.json noticepolicies.json requestpolicies.json


