#!/bin/bash
tablenames=$(mysql folio -e "show tables;" -B |sed "1d")

IFS=$'\n'

tables=($tablenames)

for table in ${tables[@]}; do
	mysql folio -e "select * from ${table}" -B > "${table}.tsv" 
done


