#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

SECONDS=0

while IFS=$'\t' read -r name description;do

if [[ $SECONDS -gt 500 ]]; then
	auth 2>/dev/null || authn 2>/dev/null
	okapi_token=$(cat okapi.token)
	SECONDS=0
fi
deptid=$(uuidgen)

IFS='' read -r -d '' newDept << EndOfDept
{
"id": "${deptid}",
"name": "${name}",
"description": "${description}"
}
EndOfDept

apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${newDept}" "${okapi_url}/coursereserves/departments")
echo -e "${apicall}" 

done < depts


