#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

jobexecution_id=$(tr -dc "[0-9a-f\-]" <<< $1)

if [[ -z $jobexecution_id ]];then
	echo "You must supply a job execution ID"
	exit
fi

curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-export/job-executions?query=status=(COMPLETED%20OR%20COMPLETED_WITH_ERRORS%20OR%20FAIL)%20sortBy%20completedDate/sort.descending&limit=25" |jq -r ".jobExecutions[] |select(.id == \"${jobexecution_id}\")"

