#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

jobexecution_id=$(tr -dc "[0-9a-f\-]" <<< $1)

if [[ -z $jobexecution_id ]];then
	echo "You must supply a job execution ID"
	exit
fi

apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/metadata-provider/jobLogEntries/${jobexecution_id}?limit=10000" | jq -c '.entries[]')

echo "Errors:" 
echo "${apicall}"| jq -cr 'select(.error != "") | 
if .error |startswith("io.vertx.core.impl.NoStackTraceThrowable") then
	.error
else 
	.error|fromjson|.errors[].message
end' |sed 's/\\n.*//' |sort |uniq -c |sort -k1nr

echo "${apicall}" > diresults.json
echo "Full results have been sent to 'diresults.json'"

