#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

jobexecution_id=$(tr -dc "[0-9a-f\-]" <<< $1)

if [[ -z $jobexecution_id ]];then
	echo "You must supply a job execution ID"
	exit
fi

apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/metadata-provider/jobLogEntries/${jobexecution_id}?limit=10000" | jq -c '.entries[]')

echo "Errors:" 
echo "${apicall}" | jq -c 'select(.error != "") |.error|fromjson|.errors[].message'|sed 's/\\n.*//' |tr -d '"' |sort |uniq -c |sort -k1nr

echo "${apicall}" |jq -r 'select(.sourceRecordActionStatus=="DISCARDED") |.incomingRecordId' > discarded_ids
echo "Discarded ids have been sent to 'discarded_ids'"

