#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

jobexecution_id=$(tr -dc "[0-9a-f\-]" <<< $1)

if [[ -z $jobexecution_id ]];then
	echo "You must supply a job execution ID"
	exit
fi

curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/metadata-provider/jobLogEntries/${jobexecution_id}?limit=100&order=asc"

