#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# retrieves item and holdings data associated with
# an instance
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

search=${1}

if [[ ${search} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
        instance_uuid=${search}
fi

if [[ ${instance_uuid} != "" ]];then
	curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/search/instances/facets?facet=holdings.tenantId&query=id=${instance_uuid}" |jq -r '.facets."holdings.tenantId"'
fi
