#!/usr/bin/bash
echo "Exporting bibs"
export-all instances
echo "Exporting holdings"
export-all holdings

echo "Retrieving items"
records-get items
records-get locations
records-get mattypes 
records-get loantypes
records-get holdingstypes


echo
echo "Retrieving reference data"
jq -r '[.id, .code]|@tsv' locations.json > location.tsv
jq -r '[.id, .name]|@tsv' mattypes.json > mattype.tsv
jq -r '[.id, .name]|@tsv' loantypes.json > loantype.tsv

echo -e "id\thrid\tholdingsId\tlocation\tmattype\tloantype\tbarcode\tcopy\tvolume\tstatus\tcallNumber\tcheckin_notes\tcheckout_notes\tpublic_notes\tstaff_notes\tadministrativeNotes" > items.tsv

echo
echo "Extracting item records."
pv items.json |jq -r --arg delim "${delim}" --arg subdelim "${subdelim}" '
	[
	"\(.id)" // "",
	"\(.hrid)" // "",
	"\(.holdingsRecordId)" // "",
	"\(.effectiveLocationId)" // "",
	"\(.materialTypeId)" // "",
	"\(.permanentLoanTypeId)" // "",
	"\(.barcode)" // "",
	"\(.copy)" // "",
	"\(.volume)" // "",
	"\(.status.name)" // "",
	"\(.effectiveCallNumberComponents.callNumber)" // "",
	"\([ .circulationNotes[] |select(.noteType=="Check in") | .note ] |join($subdelim))" // "",
	"\([ .circulationNotes[] |select(.noteType=="Check out") | .note ] |join($subdelim))" // "",
	"\([ .notes[] |select(.staffOnly==false) | .note ] |join($subdelim))" // "",
	"\([ .notes[] |select(.staffOnly==true) | .note ] |join($subdelim))" // "",
	"\( .administrativeNotes |join($subdelim))" // "",
	"\(.discoverySuppress)" // false
	] |join($delim)
	' >> items.tsv 
echo
echo "Converting UUIDs to human readable values"
echo
value-mapper items.tsv

mv items_fixed.tsv items.tsv

rm location.tsv
rm mattype.tsv
rm loantype.tsv

echo "Instance IDs are exported to instanceIds.csv"
numrecs=$(wc -l instanceIds.csv |cut -d " " -f1)

if [[ $numrecs -gt 500000 ]];then 
	echo "Large instance file with $numrecs records detected"
	echo "Splitting into smaller files is recommended"
fi
echo "Bib and holdings files are saved as MARC files"
echo "Item records have been exported to items.tsv"
echo
