#!/usr/bin/bash

workingdir=$(pwd)
profileName="DCB MelCat Export"
fromDate=$(date -I --date '1 month ago')
toDate=$(date -I)

idfile="search.cql"
tenant="fs0000xxxx"

user="username"
pass="password"
okapi_url="https://api-xxxxxx.folio.ebsco.com"

okapi_login=$(jq -n --arg TENANT ${tenant} --arg USER ${user} --arg PASS ${pass} '{ "tenant": $TENANT, "username": $USER, "password": $PASS }')

okapi_token=$(curl -c - -s -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -d "${okapi_login}" "${okapi_url}/authn/login-with-expiry" |grep folioAccessToken| cut -f7)

echo "(metadata.createdDate>=\"${fromDate}\" and metadata.createdDate<=\"${toDate}\")" > ${idfile}

errors=0
status=""
SECONDS=0
OFFSET=0

upload_file() {
	idfile="$1"

	apicall=$(curl --http1.1 -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-export/job-profiles?limit=1000")

	jobProfileId=$(echo "${apicall}" |jq -r ".jobProfiles[] | select(.name==\"${profileName}\") | .id")

	if ! [[ $jobProfileId =~ [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12} ]]; then
		echo "No valid profile found. Exiting."
		exit
	fi

	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "{\"fileName\": \"${idfile}\", \"uploadFormat\":\"cql\"}" "${okapi_url}/data-export/file-definitions")

	fileDefinitionId=$(echo ${apicall} |jq -r .id)	
	jobExecutionId=$(echo ${apicall} |jq -r .jobExecutionId)
	echo "${jobExecutionId}" > ${workingdir}/.jobid
	echo "${fileDefinitionId}" > ${workingdir}/.fileid

	apicall=$(curl --http1.1 -s -w '\n' -X POST  -H "Content-type: application/octet-stream" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" --data-binary @${idfile} "${okapi_url}/data-export/file-definitions/${fileDefinitionId}/upload")

	payload="{\"fileDefinitionId\": \"${fileDefinitionId}\", \"jobProfileId\": \"${jobProfileId}\", \"idType\": \"instance\"}"
	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${payload}" "${okapi_url}/data-export/export")

	echo "${apicall}"
}

process_file() {
	idfile="${1}"

	upload_file "${idfile}"
	checkfile=""

	while [[ ! ${checkfile} =~ [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12} ]];do
		if [[ $SECONDS -gt 500 ]]; then
			okapi_token=$(curl -c - -s -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -d "${okapi_login}" "${okapi_url}/authn/login-with-expiry" |grep folioAccessToken| cut -f7)
			SECONDS=1
			OFFSET=$(($OFFSET + 1))
		fi

		TIMER=$(($OFFSET * 500 + $SECONDS))

		sleep 5
		jobExecutionId=$(cat "${workingdir}/.jobid")
		apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-export/job-executions?query=id==${jobExecutionId}" |jq '.jobExecutions[0]') 

		status=$(echo ${apicall} |jq -r .status)
		exported=$(echo "${apicall}" |jq -r .progress.exported)
		failed=$(echo "${apicall}" |jq -r .progress.failed)
		total=$(echo "${apicall}" |jq -r .progress.total)

		if [[ $status =~ ^COMPLETED.* ]] || [[ $status =~ ^FAIL.* ]];then
			checkfile=$(echo ${apicall} |jq -r '.exportedFiles[0].fileId')
		fi

		echo -en "Status: ${status} Exported: ${exported} Failed: ${failed}: Total: ${total} JobId: $jobExecutionId    \r"
	done

	sleep 5

	fileId=$(echo "${apicall}" |jq -r '.exportedFiles[0].fileId')
	fileName=$(echo "${apicall}" |jq -r '.exportedFiles[0].fileName')

	apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-export/job-executions/${jobExecutionId}/download/${fileId}") 
	link=$(echo ${apicall} |jq -r .link)

	echo "Status: ${status} Exported: ${exported} Failed: ${failed}: Total: ${total}	JobId: $jobExecutionId"
	curl -w '\n' -o "${workingdir}/${fileName}" -X GET -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${link}" 
	echo "Output sent to ${fileName}"

}

echo "Processing ${idfile}"

process_file "${idfile}"

TIME=$TIMER;msg="$TIMER seconds"
if [[ $TIMER -gt 60 ]];then TIME=$(($TIMER/60));msg="$TIME minutes";fi
if [[ $TIMER -gt 3600 ]];then TIME=$(($TIMER/3600));msg="$TIME hours";fi

echo "Processing ${msg} elapsed"
	
