#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
#0cf-e4aa278110b7 expects fine amounts in column 1, patron uuid in column 2

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)
infile="waive.tsv"
logile="waive.log"

SECONDS=1
TIMEROFFSET=0


while IFS=$'\t' read -r account_id amount; do

	if [[ $SECONDS -gt 500 ]]; then
		TIMEROFFSET=$(($TIMEROFFSET + 1))
		auth 2>/dev/null || authn 2>/dev/null
		okapi_token=$(cat okapi.token)
		SECONDS=1
	fi

	TIMER=$(($TIMEROFFSET * 500 + $SECONDS))
	TIME=$TIMER;msg="$TIMER seconds"
	if [[ $TIMER -gt 60 ]];then TIME=$(($TIMER/60));msg="$TIME minutes";fi
	if [[ $TIMER -gt 3600 ]];then TIME=$(($TIMER/3600));msg="$TIME hours";fi
	echo -en "Processing record $counter of $numrecs in $msg in $(($counter/$TIMER)) recs/sec\r"

IFS='' read -r -d '' fine << EndOfJSON
{
  "amount": "${amount}",
  "paymentMethod": "Library/system error",
  "notifyPatron":false,
  "comments":"STAFF : Automatic wave",
  "servicePointId":"22b564d4-5cb0-4d5a-9358-f7e25e3d8fad",
  "userName":"admin, admin"
}
EndOfJSON


	apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${fine}" "${okapi_url}/accounts/${account_id}/waive")

	echo -e "${apicall//$'\n'/ }" >> ${logfile}


done < ${infile}

echo "$numrecs records have been exported to ${outfile}"
