#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

infile="funds.tsv"
defaultacqunit="KU Main Collection"
defaultfiscalyear="FY2027"
defaultledger="027 State"
currentYear="2027"

apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/finance/expense-classes?query=cql.allRecords=1&limit=100000")

declare -A acqUnit
declare -A group
declare -A ledger
declare -A fiscalYear

eval "$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/acquisitions-units/units?query=cql.allRecords=1&limit=1000" |jq -r '.acquisitionsUnits[] | @sh "acqUnit[\(.name|tostring|ascii_downcase |gsub("[^0-9a-z]"; ""))]=\(.id|tostring)"')"

eval "$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/finance/groups?query=cql.allRecords=1&limit=1000" |jq -r '.groups[] | @sh "group[\(.code|tostring|ascii_downcase |gsub("[^0-9a-z]"; ""))]=\(.id|tostring)";group[\(.name|tostring|ascii_downcase |gsub("[^0-9a-z]"; ""))]=\(.id|tostring)')"


ledgers=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/finance/ledgers?query=cql.allRecords=1%20sortby%20value&limit=100")

fiscalYears=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/finance/fiscal-years?query=cql.allRecords=1%20sortby%20value&limit=100")

eval "$(echo ${ledgers} |jq -r '.ledgers[] | @sh "ledger[\(.code|tostring)]=\(.id|tostring);ledger[\(.name|tostring|ascii_downcase |gsub("[^0-9a-z]"; ""))]=\(.id|tostring)"')"
eval "$(echo ${fiscalYears} |jq -r '.fiscalYears[] | @sh "fiscalYear[\(.code|tostring)]=\(.id|tostring|ascii_downcase |gsub("[^0-9a-z]"; "")); fiscalYear[\(.name)]=\(.id|tostring)"')"

## load programs, split each line into array
while IFS=$'\n' read -r line; do
        #IFS=$'\t' read fundname fundcode externalAccount description allocated <<< ${line}
        IFS=$'\t' read fundname fundcode acqunit fundgroup externalAccount allocated <<< ${line}

	[[ -z ${acqunit} ]] && fiscalyear=${defaultacqunit}
	[[ -z ${fiscalyear} ]] && fiscalyear=${defaultfiscalyear}
	[[ -z ${ledger} ]] && fiscalyear=${defaultledger}

	acqunit=${acqunit,,}
	acqunit=${acqunit//[^0-9a-z]/}
	acqunitId=${acqUnit["${acqunit}"]} 
	[[ ${acqunitId} =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] && acqUnitId="\"${acqunitId}\""

	fiscalyear=${fiscalyear,,}
	fiscalyear=${fiscalyear//[^0-9a-z]/}
	fiscalyearId=${fiscalYear["${fiscalyear}"]} 
	[[ ${fiscalyearId} =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] && fiscalyearId="\"${fiscalyearId}\""

	ledger=${ledger,,}
	ledger=${ledger//[^0-9a-z]/}
	ledgerId=${ledger["${ledger}"]} 
	[[ ${ledgerId} =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] && ledgerId="\"${ledgerId}\""

	fundgroup=$(echo "${fundgroup}" |tr [A-Z] [a-z] |tr -dc [0-9a-z])
	groupId=${group[${fundgroup}]}

	[[ ${groupId} =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] && groupId="\"${groupId}\""

	[[ -z $fundcode ]] && fundcode="${fundname}"
	[[ -z $fundname ]] && fundname="${fundcode}"
	[[ ${#externalAccount} -lt 1 ]] && externalAccount="-"
	[[ -z ${allocated} ]] && allocated=0

	allocated=$(printf "%.2f" ${allocated//[^0-9\/.]/})

	funduuid=$(uuidgen)
	budgetuuid=$(uuidgen)

	### build the fund

	funddata="{\"fund\": { \"id\": \"${funduuid}\", \"fundStatus\":\"Active\",\"name\":\"${fundname}\",\"code\":\"${fundcode}\",\"description\": \"${description}\",\"ledgerId\":\"${ledger}\",\"externalAccountNo\":\"${externalAccount}\", \"acqUnitIds\": [${acqUnitId}]}, \"groupIds\": [${groupId}] }"

	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${funddata}" "${okapi_url}/finance/funds"

	### add a budget

	budgetdata="{${expenseclassobject}, \"fiscalYearId\":\"${fiscalyear}\",\"budgetStatus\":\"Active\",\"allowableExpenditure\":100,\"allowableEncumbrance\":100,\"allocated\":\"${allocated}\",\"fundId\":\"${funduuid}\",\"name\":\"${fundcode}-FY${currentYear}\",\"id\":\"${budgetuuid}\"}"

	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${budgetdata}" "${okapi_url}/finance/budgets"

done < "${infile}"
