#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

infile=holdings.json
outfile=holdings_update.log
searchtype="id"

batchsize=50

if [[ ! -f ${infile} ]];then echo "Expected ${infile} file not found";fi

jq_replace='.holdingsRecords[].permanentLocationId="3ca852c2-67a8-4cf1-8b5e-3ce376943c8e" '

querydelim="%20or%20${searchtype}="
endpoint="${okapi_url}/holdings-storage/holdings?query="

rm -f ${outfile}

counter=0
numrecs=$(wc -l ${infile} |cut -d " " -f1)

while mapfile -t -n ${batchsize} ids && ((${#ids[@]})); do
	counter=$(($counter + ${#ids[@]}))

	# break array into space separated string
	idstring="${ids[@]}"
	querystring="id=${idstring// /${querydelim}}"

	records=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${endpoint}${querystring}&limit=${batchsize}")

	updated_records=$(echo "${records}" |jq -c "${jq_replace} | del(.totalRecords) |del(.resultInfo)")

	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "Accept: text/plain" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${updated_records}" "${okapi_url}/holdings-storage/batch/synchronous?upsert=true" >> ${outfile}

	printf "Processing record %s of %s\r" $counter $numrecs

done < ${infile}

echo "Processed ${numrecs} records. Output was written to ${outfile}"



