#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# retrieves item and holdings data associated with
# an instance
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

idtype=${1}

case ${idtype} in
	"instances"):
		good=1;;
	"holdings"):
		good=1;;
	*):
		echo "You must select instances or holdings"
		exit
esac
	

echo "Retrieving all ids. Please be patient"

curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/search/${idtype}/ids?query=cql.allRecords=1" |pv |jq -r .ids[].id > ids

echo 
numrecs=$(wc -l ids |cut -d " " -f1)
echo "${numrecs} ids have been exported to ids"
echo
