#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

profile=$(tr -dc "[a-f0-9\-]" <<< $1)

curl --http1.1 -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-import-profiles/profileSnapshots/${profile}?profileType=JOB_PROFILE&profile=${profile}" |jq -c 'del(..| .metadata?, .userInfo?)' > importprofile.json


echo "Import profile has been exported to importprofile.json"
