#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# retrieves item and holdings data associated with
# an instance

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

instance_uuid="$1"

apicall=$(curl -s -w '\n' -X GET -D \
  -H "Accept: application/json" \
  -H "X-Okapi-Tenant: ${tenant}" \
  -H "x-okapi-token: ${okapi_token}" \
  "${okapi_url}/instance-storage/instances/${instance_uuid}")
echo $apicall 

