#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

[[ -z ${1} ]] && echo "You must supply an item damaged status";exit

damaged_status="${1}"

IFS='' read -r -d '' damaged << EndOfProfile
{
    "id" : "$(uuidgen)",
    "name" : "${damaged_status}",
    "source": "local"
}
EndOfProfile

curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${damaged}" "${okapi_url}/item-damaged-statuses"
