#!/bin/bash

infile=${1}
if [[ -z ${infile} ]]; then echo "You must specify an input file";exit;fi
echo "Item UUIDs are expected in the first column and Holdings UUIDs are expected in the second column"
echo
outfile="moveitems.json"

rm -f ${outfile}

awk -F'\t' '
{
  # Group itemIds by holdingsId
  if (length(items[$2]) == 0) {
    items[$2] = $1
  } else {
    items[$2] = items[$2] "," $1
  }
	if (NR % 10000 == 0){ printf "Records analyzed: "NR"\r" }
}
END {
	print ""
	counter=1
  for (h in items) {
    split(items[h], id_array, ",")
    printf "{ \"toHoldingsRecordId\": \"%s\", \"itemIds\": [", h >> "'"$outfile"'"
    for (i = 1; i <= length(id_array); i++) {
      printf "\"%s\"", id_array[i] >> "'"$outfile"'"
      if (i < length(id_array)) {
        printf ", " >> "'"$outfile"'"
      }
    }
    print "] }" >> "'"$outfile"'"
		if (counter % 10000 == 0){ printf "Records created: "counter"\r" }
		counter++
  }
}
' "$infile"
echo

records-post moveitems
