#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

IFS='' read -r -d '' data << EndOfJSON
{
  "id": "$(uuid)",
  "name": "${1}",
	"source": "local"
}
EndOfJSON


curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${data}" "${okapi_url}/item-note-types"



