#!/usr/bin/bash

if [[ -z ${3} ]];then
	echo "Extracts records from a JSON file using a matching file with values for a specified key"
	echo "Use the not keyword to select records that do not match"
	echo "Output is to stdout"
	echo "JSON key must be specified in jq syntax minus leading dot in first element"
	echo
	echo "Usage: jqextractbykey [jsonfile] [valuefile] [jsonkey]"
	echo
	echo "Example: jqextractbykey myfile.json ids id"
	echo "Example: jqextractbykey myfile.json ids id not"
	exit
else
	jsonfile="${1}"
	valuefile="${2}"
	jsonkey="${3}"
fi

	cat "${valuefile}" |jq -R . > "tmp_vals"

if [[ ${4} == "not" ]];then
	jq -c --slurpfile all_values tmp_vals --arg KEY "${jsonkey}" 'select(.[$KEY] | IN($all_values[]) |not) ' "${jsonfile}"
else
	jq -c --slurpfile all_values tmp_vals --arg KEY "${jsonkey}" 'select(.[$KEY] | IN($all_values[])) ' "${jsonfile}"
fi

rm tmp_vals
