#!/usr/bin/bash

if [[ -z ${3} ]];then
	echo "Maps values in a two column tab delimited file into a JSON document based on key matchpointy"
	echo "Use the not keyword to select records that do not match"
	echo "Output is to stdout"
	echo "JSON key must be specified in jq syntax"
	echo
	echo "Usage: jqmap [jsonfile] [mapfile] [jsonkey]"
	echo
	echo "Example: jqmap myfile.json barcode_id .id"
	exit
else
	json_file="${1}"
	map_file="${2}"
	jsonkey="${3}"
	fileroot=$(echo "${json_file}" | sed 's/\.....\?$//')
	outfile="${fileroot}_remapped.json"
fi

jq -rRn '
	 reduce inputs as $line ({};
		($line | split("\t") | .[0]) as $key |
		($line | split("\t") | .[1]) as $value |
		. + { ($key): $value }
	)
' ${map_file} > tmp_map

pv  ${json_file} | jq --argfile key_value tmp_map --arg KEY ${jsonkey} '
	$key_value[.[$KEY]] as $value
	| if $value != null then .[$KEY] = $value else . end
' > ${outfile}

rm tmp_map
echo "A remapped file has been sent to ${outfile}"
echo
