#!/usr/bin/env bash

# usage:
#   ./jqsearch [-i] [-k] "regex" [filename]
#   cat file.json | ./jqsearch [-i] [-k] "regex"

IGNORE_CASE=0
KEY_SEARCH=0

while getopts "ik" opt; do
  case $opt in
    i) IGNORE_CASE=1 ;;
    k) KEY_SEARCH=1 ;;
  esac
done
shift $((OPTIND - 1))

# require at least one positional argument (the regex)
if [[ -z "$1" ]]; then
  echo "Usage: jqsearch [-i] [-k] \"regex\" [filename]" >&2
  exit 1
fi

REGEX="$1"
FILE="$2"

if [[ $IGNORE_CASE -eq 1 ]]; then
  JQ_TEST='test($REGEX; "i")'
else
  JQ_TEST='test($REGEX)'
fi

# stdin vs file
INPUT="${FILE:--}"

jq -r --arg REGEX "$REGEX" --argjson KEY_SEARCH "$KEY_SEARCH" '
  . as $data
  | [
      (if $KEY_SEARCH == 1 then
         path(..)
       else
         path(.. | select(scalars and (tostring | '"$JQ_TEST"')))
       end
      ) as $p

      | select(
          if $KEY_SEARCH == 1 then
            ($p[-1] | type == "string" and ($p[-1] | '"$JQ_TEST"'))
          else
            true
          end
        )

      | {
          (
            reduce $p[] as $x ("";
              if ($x|type) == "number" then
                . + "[" + ($x|tostring) + "]"
              else
                if . == "" then
                  $x
                else
                  . + "." + $x
                end
              end
            )
          ): ($data | getpath($p))
        }
    ]
  | add
' "$INPUT"
