#!/usr/bin/env bash

# usage:
#   ./jqsearch [-i] "regex" filename

IGNORE_CASE=0

while getopts "i" opt; do
  case $opt in
    i) IGNORE_CASE=1 ;;
  esac
done
shift $((OPTIND - 1))

REGEX="$1"
FILE="$2"

if [[ $IGNORE_CASE -eq 1 ]]; then
  JQ_TEST='test($REGEX; "i")'
else
  JQ_TEST='test($REGEX)'
fi

jq -r --arg REGEX "$REGEX" "
  . as \$data
  | [
      path(.. | select(scalars and (tostring | $JQ_TEST))) as \$p
      | {
          (
            # build path string to match jq syntax
            reduce \$p[] as \$x (\"\"; 
              if (\$x|type) == \"number\" then
                . + \"[\" + (\$x|tostring) + \"]\"
              else
                if . == \"\" then
                  \$x
                else
                  . + \".\" + \$x
                end
              end
            )
          ): \$data | getpath(\$p)
        }
    ]
  | add
" "$FILE"

