#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

license_name="${1}"

license=$(curl  -s -w '\n' --data-urlencode "match=name" --data-urlencode "perPage=100" --data-urlencode "term=${license_name}" -G -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/licenses/licenses")

echo "${license}" | jq ".[] |select(.name==\"${license_name}\")" 
