#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# updates all items that are not Declared lost, Restricted, or missing to Available 

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

SECONDS=1

echo "Retrieving records requring update"
records-get items 'status.name=="Aged%20to%20lost"%20or%20status.name=="Checked%20out"%20or%20status.name=="In%20transit"%20or%20status.name=="Paged"'

echo "Setting status to Available"

infile=loan_uuids

jq -c '.status.name="Available"' items.json > tmp.json
mv tmp.json items.json

inventory-replace items
