#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

search="$1"


if [[ ${search} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
	endpoint="${okapi_url}/locations/${search}"
else
	endpoint="${okapi_url}/locations?query=code=${search}"
	code=1
fi

if [[ $search != "" ]];then
	apicall=$(curl -s -w '\n' -X GET -D \
	  -H "Accept: application/json" \
	  -H "X-Okapi-Tenant: ${tenant}" \
	  -H "x-okapi-token: ${okapi_token}" \
	  "${endpoint}")
	
	echo $apicall |jq '.'
else
	apicall=$(curl -s -w '\n' -X GET -D \
	  -H "Accept: application/json" \
	  -H "X-Okapi-Tenant: ${tenant}" \
	  -H "x-okapi-token: ${okapi_token}" \
	  "${okapi_url}/locations?limit=0")

	echo ${apicall}
fi
	

