#!/usr/bin/bash

while getopts "hiouv" opt; do
  case $opt in
	h)
	  filetype="holdings"
	  ;;
		i) 
			filetype="item"
			;;
		o) 
			filetype="composite_order"
			;;
		u) 
			filetype="user"
			;;
		v) 
			filetype="organization"
			;;
	\?)
		echo "Error: Invalid option -$OPTARG" >&2
		echo "Usage: $0 [-hiouv]" >&2
		exit 1
		;;
  esac
done

shift $((OPTIND - 1))

infile="${1}"

if [[ ! -f ${infile} ]] || [[ -z ${filetype} ]];then 
cat << EOF

You must supply a file name and supply a switch to indicate filetype.

File types: 
	-h: holdings
	-i: item (also builds holdings)
	-o: order
	-u: user
	-v: organizations

EOF
	exit
fi

IFS= read -r -d '' item_statuses <<'EOF'
legacy_code	folio_name
m	Missing
$	Lost and paid
o	Restricted
w	Withdrawn
p	In process
z	Claimed returned
!	Awaiting pickup
n	Aged to lost
b	In process
At Bindery	In process (non-requestable)
Claimed Returned	Claimed returned
In Process	In process
In process (non-requestable)	In process (non-requestable)
Lib Use Only	Restricted
Library use only	Restricted
Lost	Lost
Lost--System Applied	Lost
Withdrawn	Withdrawn
BINDERY In process (non-requestable)
CATALOGING  In process
CLAIMED_RETURNED  Claimed returned
DAMAGED In process (non-requestable)
DISCARD Withdrawn
DISPATCHED  In transit
INPROCESS In process
IN_PROCESSING In process
LOST  Lost and paid
LOST-ASSUM  Missing
LOST-CLAIM  Declared lost
LOST-CLAIM  Missing
LOST-PAID Lost and paid
NON-CIRC  Restricted
RESTRICTED  Restricted
WITHDRAWN Withdrawn
EOF

note_iter=0
address_iter=0
chkinnote_iter=0
chkoutnote_iter=0
phone_iter=0

### convert indexed array to associative array

IFS=$'\t' read -r -a hdr < <(head -n 1 -- "$infile")
declare -A header_arr

for i in "${!hdr[@]}"; do header_arr["${hdr[$i]}"]="${hdr[$i]}";done

addfield() {
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"\"}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addbackupfield() {
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"\",\"legacy_backupfield\":\"${2}\"}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addvalue() {
	value="${2}"
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"${2}\"}"
	newfield=$(sed 's/"\(true\|false\)"/\1/' <<< "${newfield}")
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addreplacerules() {
	replace_rule="${2}"
	[[ "${2}" == "truefalse" ]] && replace_rule='"Yes":"true","YES":"true","Y":"true","y":"true","n":"false","N":"false","TRUE":"true","No":"false","NO":"false","FALSE":"false"'

	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"\",\"rules\":{\"replaceValues\":{${replace_rule}}}}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addregexrules() {
	regex_rule="${2}"
	[[ "${2}" == "currency" ]] && regex_rule='([0-9]+\\.[0-9]{2})'
	[[ "${2}" == "email" ]] && regex_rule='(^[a-zA-Z0-9_\\-\\.]+@[a-zA-Z0-9_\\-\\.]+)'
	[[ "${2}" == "number" ]] && regex_rule='([0-9]+)'
	[[ "${2}" == "url" ]] && regex_rule='(^http.*)'

	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"\",\"rules\":{\"regexGetFirstMatchOrEmpty\":\"${regex_rule}\"}}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

default_field() {
  local target_folio_field="$1"
  local source_folio_field="$2"

  object_map=$(jq --arg target "$target_folio_field" --arg source "$source_folio_field" '
	if any(.data[]; .folio_field == $target) then
	  .
	else
	  .data += [{
		folio_field: $target,
		legacy_field: (
		  first(
			.data[]
			| select(.folio_field == $source)
			| .legacy_field
		  )
		)
	  }]
	end
  ' <<< "${object_map}")
}

default_value() {
  local key="$1"
  local value="$2"

  object_map=$(jq --arg key "$key" --arg value "$value" '
	.data |= map(
	  if .folio_field == $key
	  then . + { value: $value }
	  else .
	  end
	)
  ' <<< "${object_map}")
}

fallback_value() {
  local key="$1"
  local value="$2"

  object_map=$(jq --arg key "$key" --arg value "$value" '
	.data |= map(
	  if .folio_field == $key
	  then . + { fallback_legacy_value: $value }
	  else .
	  end
	)
  ' <<< "${object_map}")
}

initialize() {
	object_map='{"data":[]}'
	outfile="${filetype}_mapping.json"
}

print_results() {
	jq '.data |= (sort_by(.folio_field) | map(. + {description: ""}))' <<< "${object_map}" \
	  | sed 's/"true"/true/;s/"false"/false/' > "${outfile}"
	{
	  echo -e "Legacy field\tFOLIO field"
	  jq -r '.data[] | [.legacy_field, .folio_field] | @tsv' "${outfile}"
	} > tmpmap
	
	echo "MAPPED and UNMAPPED fields from ${infile} output to ${outfile}"
	echo "Delimited map templates have been created"
	echo
	
	jq -r '.data[].legacy_field' "${outfile}" | sort -u > tmp1
	head -1 "${infile}" | tr '\t' '\n' | sort -u > tmp2
	awk -v FS='\t' '
	  NR==FNR { seen[$1]=1; next }
	  !($1 in seen) { print $1 }
	' tmp1 tmp2 > tmpunmapped1
	
	{
	  echo "UNMAPPED legacy fields found in ${infile}"
	  cat tmpunmapped1
	} > tmpunmapped2
	
	paste -d $'\t' tmpmap tmpunmapped2 | column -t -s $'\t'
	
	rm -f tmp1 tmp2 tmpunmapped1 tmpunmapped2 tmpmap
}

build_order_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(echo "${field,,}" | tr -dc "[a-z0-9]" |sed 's/folio//' )
	
	case ${comp_field} in
	  acqtype | acquisitionmethod | ordtype )
			addfield compositePoLines[0].acquisitionMethod
			default_value compositePoLines[0].acquisitionMethod Other
			acqMethod="${field}"
		;;
	  approved )
				addreplacerules approved truefalse
		;;
	  currency )
			addfield compositePoLines[0].cost.currency
		;;
	  	eprice | price | listunitprice | polineestimatedprice | unitprice )
			addregexrules compositePoLines[0].cost.listUnitPrice currency
			default_value compositePoLines[0].cost.listUnitPrice "0"
			addregexrules totalEstimatedPrice currency
			default_value totalEstimatedPrice "0"
		;;
	  listunitpriceelectronic )
			addregexrules compositePoLines[0].cost.listUnitPriceElectronic currency
			default_value compositePoLines[0].cost.listUnitPriceElectronic "0"
		;;
	  listunitpricephysical )
			addregexrules compositePoLines[0].cost.listUnitPricePhysical currency
			default_value compositePoLines[0].cost.listUnitPricePhysical "0"
		;;
	  costquantityelectronic | quantityelectronic )
			addregexrules compositePoLines[0].cost.quantityElectronic number
			default_value  compositePoLines[0].cost.quantityElectronic "0"
		;;
	  costquantityphysical | quantity | quantityphysical )
			addregexrules compositePoLines[0].cost.quantityPhysical number
			default_value  compositePoLines[0].cost.quantityPhysical "0"
		;;
	  descriptionreceivingnote | detailsreceivingnote | receivingnote )
			addfield compositePoLines[0].details.receivingNote
		;;
	  url )
				addregexrules compositePoLines[0].details.resourceUrl url
		;;
	  startdate )
			addfield compositePoLines[0].details.subscriptionFrom
		;;
	  expirationdate )
			addfield compositePoLines[0].details.subscriptionTo
		;;
	  polinenote | polnote)
			addfield compositePoLines[0].description
		;;
	  bibid | bibno | mmsid | mmsrecordid | recordbiblio | recordbibliographic | recordnumberbibliographic | systemidentifierbibid )
		addfield compositePoLines[0].instanceId
		;;
	  location | locationcode | locationidcode )
			addfield compositePoLines[0].locations.[0].locationId
			locationfield="${field}"
		;;
	  copies | quantity | quantitytotal | totalitems )
			addregexrules compositePoLines[0].locations[0].quantity number
		;;
	  locationquantityelectronic | quantityelectronic )
			addregexrules compositePoLines[0].locations[0].quantityElectronic number
			default_value compositePoLines[0].locations[0].quantityElectronic "0"
		;;
	  locationquantityphysical | quantityphysical )
			addregexrules compositePoLines[0].locations[0].quantityPhysical number
			default_value compositePoLines[0].locations[0].quantityPhysical "0"
		;;
	  form | format | orderformat )
			addfield compositePoLines[0].orderFormat
			default_value compositePoLines[0].orderFormat Physical
		;;
	  publishername )
			addfield compositePoLines[0].publisher
		;;
	  requester )
			addfield compositePoLines[0].requester
		;;
	  title | titleorpackage )
			addfield compositePoLines[0].titleOrPackage
		;;
	  approvaldate | dateordered | invoicedate | odate | podate )
		addfield dateOrdered
		;;
	  expenseclass | fund | fundcode | vendorinstruction )
			addfield notes[${note_iter}]
			addvalue notes[${note_iter}] "(${field})"
			note_iter=$(($note_iter + 1))
		;;
	  note | ordernote | descriptioninternalnote )
			addfield notes[${note_iter}]
			note_iter=$(($note_iter + 1))
		;;
	  intnote | ongoingnote )
			addfield ongoing.notes
		;;
	  ongoingissubscription )
			addreplacerules ongoing.isSubscription truefalse
		;;
	  ongoingmanualrenewal )
			addreplacerules ongoing.manualrenewal truefalse
		;;
	  lineitemtype | ordtype | ordertype )
			addreplacerules orderType '"Single-part":"One-Time","Subscription":"Ongoing","Standing order":"Ongoing","ongoing":"Ongoing", "one-time":"One-Time"'
			addreplacerules ongoing.isSubscription '"Single-part":"false","Subscription":"true","Standing order":"false"'
			addvalue ongoing.manualRenewal true
		;;
	  almapoline | ordernumber | po | ponumber | purchaseordernumber | recordorder )
			addfield poNumber
			addfield legacyIdentifier
			addvalue compositePoLines[0].source API
		;;
	  poprefix )
			addfield poNumberPrefix
		;;
	  posuffix )
			addfield poNumberSuffix
		;;
	  reencumber | renewaldate )
			addfield reEncumber
		;;
	  totalcost | totalprice )
			addregexrules totalEstimatedPrice currency
		;;
			organization | vendor | vendorcode )
			addfield vendor
			vendorfield="${field}"
		;;
	  workflowstatus )
			addvalue workflowStatus Pending
		;;
	esac

	default_field workflowStatus poNumber
	default_value workflowStatus Pending

	[[ -n ${vendorfield} ]] && echo -e "${vendorfield}\tfolio_name\n" > organizationCodeMap.tsv
done

	[[ -n ${acqMethod} ]] && echo -e "${acqMethod}\tfolio_value\nApproval\tApproval plan\nApproval Plan\tApproval plan\nDemand Driven Acquisitions (DDA)\tDemand Driven Acquisitions (DDA)\nDepository\tDepository\nExchange\tExchange\nFirm Order\tPurchase\nFree\tFree\nGift\tGift\nMembership\tMembership\nMembership Title\tMembership\nPurchase at Vendor System\tPurchase at vendor system\nc\tPurchase\nm\tMembership\np\tPurchase\nt\tPurchase\n*\tOther" > acquisitionMethodMap.tsv
	[[ -n ${locationfield} ]] && echo -e "${locationfield}\tlegacy_code\tfolio_code\n*\t*\tmigration" > locations_orders.tsv
}

build_holdings_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			bibid | bibno | mmsid | mmsrecordid | recordbiblio | recordbibliographic | recordnumberbibliographic | systemidentifierbibid )
				addfield instanceId
				bibfield="${field}"
				;;
			id | itemid | itempid | physicalitemid | recorditem | z30reckey)
				addfield legacyIdentifier
				itemfield="${field}"
				;;
			callitem | permanentcallnumber | shelfmark )
				addfield callNumber 
				callfield="${field}"
				;;
			holdid | holrecordid | holdingsid | mfhdid | z30holdocunumber )
				addfield holdingsRecordId 
				holdidfield="${field}"
			;;
			holdings | libhas | libhascheckin | summaryholding | summaryholdings )
				addfield holdingsStatements[0].statement
			;;
			itempermanentlocation | itemshelvinglocation | permanentlocation | permanentphysicallocation )
				addfield permanentLocationId
				locationfield="${field}"
			;;
		esac
	done

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			call | callmarc | callno | callnumber )
				if [[ -z ${callfield} ]];then
					callfield=${field}
					addfield callNumber
				fi	
			;;
			callprefix | callnumberprefix )
				addfield callNumberPrefix
			;;
			callsuffix | callnumbersuffix )
				addfield callNumberPrefix
			;;
			oclc | oclcnumber )
				if [[ -z ${bibfield} ]];then
					bibfield=${field}
					addfield instanceId
				fi	
			;;
			loc | location )
				if [[ -z ${locationfield} ]];then
					addfield permanentLocationId
					locationfield=${field}
				fi	
			;;
		esac
	done

	# extra sweep to pull up bib specific call numbers

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			bibcall | callbiblio | callbibliographic | callnonmarc )
				if [[ -z ${callfield} ]];then
					callfield=${field}
					addfield callNumber
				fi	
			;;
		esac
	done

	if [[ -z ${holdidfield} ]];then
		field=${itemfield}
		addfield holdingsRecordId
	fi

	[[ -n ${typefield} ]] && echo -e "${mattypefield}\tfolio_name\n*\tmigration" > material_types.tsv
	[[ -n ${locationfield} ]] && echo -e "${locationfield}\tlegacy_code\tfolio_code\n*\t*\tmigration" > locations.tsv
}

build_item_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			id | itemid | itempid | physicalitemid | recorditem | z30reckey)
				addfield legacyIdentifier
				itemfield="${field}"
				;;
			barcode | itembarcode | z30barcode )
				addfield barcode
				barcodefield="${field}"
			;;
			holdid | holrecordid | holdingsid | mfhdid | z30holdocunumber )
				addfield holdingsRecordId 
				holdidfield="${field}"
			;;
			materialformat | materialtype | mattype | mtype | mediaitm | z30material )
				addfield materialTypeId 
				mattypefield="${field}"
			;;
			loantype | itempolicy )
				addfield permanentLoanTypeId 
				loantypefield="${field}"
			;;
			fulfillmentnote | imessage | imsg | messgage | checkinnote )
				addfield circulationNotes[0].note
				addvalue circulationNotes[0].noteType "Check in"
				addvalue circulationNotes[0].staffOnly true
			;;
			internalnote | intnote | staffnote )
				addfield notes[${note_iter}].note
				addvalue notes[${note_iter}].itemNoteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				addvalue notes[${note_iter}].staffOnly true
				note_iter=$(($note_iter + 1))
			;;
			note | opacmsg |publicnote | z30noteopac )
				addfield notes[${note_iter}].note
				addvalue notes[${note_iter}].noteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				addvalue notes[${note_iter}].staffOnly false
				note_iter=$(($note_iter + 1))
			;;
			copy | copynumber | copyno | copyid | z30copyid | itemcopyid )
				addfield copyNumber
			;;
			chron | chronology )
				addfield volume
			;;
			enum | enumeration | itemenum )
				addfield enumeration
			;;
			vol | volume )
				addfield volume
			;;
			year )
				addfield yearCaption[0]
			;;
			pieces)
				addfield numberOfPieces 
			;;
			itemstatus | itemstatusdesc | itemstatuscurrentstatus | status | statusmappingkey )
				addfield status.name
				statusfield="${field}"
			;;
			templocation | itemtemporaryshelvinglocation)
				addfield temporaryLocationId
			;;
		esac
	done

	

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			barcode | itembarcode | z30barcode )
				if [[ -z ${itemfield} ]];then
					addfield legacyIdentifier
					field=${itemfield}
					addfield barcode
				else
					addbackupfield barcode "${itemfield}"
				fi	
			;;
			itype | itemtypeid | itemtypecode )
				if [[ -z ${mattypefield} ]];then
					addfield materialTypeId
					mattypefield="${field}"
				fi
				if [[ -z ${loantypefield} ]];then
					addfield permanentLoanTypeId
					loantypefield="${field}"
				fi
			;;
		esac
	done

	if [[ -z ${holdidfield} ]];then
		field=${itemfield}
		addfield holdingsRecordId
	fi

	[[ -n ${mattypefield} ]] && echo -e "${mattypefield}\tfolio_name\n*\tmigration" > material_types.tsv
	[[ -n ${loantypefield} ]] && echo -e "${loantypefield}\tfolio_name\n*\tmigration" > loan_types.tsv
	echo -e "${item_statuses}" > item_statuses.tsv
}

build_organization_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			accountnum )
				addfield accounts[0].accountNo
				;;
			vendorname )
				addfield accounts[0].name
				;;
			addr1 | address1 | address11 | addressline1 )
				addfield addresses[0].addressLine1
				addvalue addresses[0].isPrimary true
				addressfield="${field}"
				;;
			addr2 | address2 | address12 | addressline2 )
				addfield addresses[0].addressLine2
				;;
			addresscategory | category )
				addfield addresses[0].categories[0]
				addresscategoryfield=${field}
				;;
			addresscity | city | city1 )
				addfield addresses[0].city
				;;
			addresscountry | country )
				addfield addresses[0].country
				;;
			addresszip | postalcode | zip | zip1 )
				addfield addresses[0].postalCode
				;;
			addressstate | region | state | state1 )
				addfield addresses[0].region
				;;
			addr21 | address21 | address2line1 )
				addfield addresses[1].addressLine1
				addvalue addresses[1].isPrimary false
				;;
			addr22 | address22 | address2line2 )
				addfield addresses[1].addressLine2
				;;
			address2category | category2 )
				addfield addresses[1].categories[0]
				;;
			address2city | city2 )
				addfield addresses[1].city
				;;
			address2country | country2 )
				addfield addresses[1].country
				;;
			address2zip | postalcode2 | zip2 )
				addfield addresses[1].postalCode
				;;
			address2state | region2 | state2 )
				addfield addresses[1].region
				;;
			altname | alternativenames )
				addfield aliases[0].value
				;;
			code | orgcode | vencode | vendorcode )
				addfield code
				codefield="${field}"
				addfield legacyIdentifier
			;;
			contact1address | contact1addressline1 )
				addfield contacts[0].addresses[0].addressLine1
			;;
			contact1addressline2 )
				addfield contacts[0].addresses[0].addressLine2
			;;
			contact1addresscity )
				addfield contacts[0].addresses[0].city
			;;
			contactfirstname | contact1fname )
				addfield contacts[0].firstName
			;;
			contactlastname | contact1lname )
				addfield contacts[0].lastName
			;;
			contactnote | contact1note )
				addfield contacts[0].notes
			;;
			description | orgnote | vendornote | vennote )
				addfield description
			;;
			email | preferredemail )
				addregexrules emails[0].value email
				addvalue emails[0].isPrimary true
				emailcategoryfield="${field}"
			;;
			accountcode | erpcode )
				addfield erpCode
			;;
			interfaceuri | url )
				addfield interfaces[0].uri
			;;
			isvendor | vendoryesno )
				addreplacerules isVendor truefalse
			;;
			name | orgname | providername | venname | vendorname )
				addfield name
			;;
			note | notes | notecontent | orgnote | vendornote | vennote )
				addfield notes[${note_iter}].content
				addvalue notes[${note_iter}].content organizations
				addvalue notes[${note_iter}].noteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				note_iter=$(($note_iter + 1))
			;;
			note2 | notes2 | notecontent2 | orgnote2 | vendornote2 | vennote2 )
				addfield notes[${note_iter}].content
				addvalue notes[${note_iter}].content organizations
				addvalue notes[${note_iter}].noteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				note_iter=$(($note_iter + 1))
			;;
			orgtype | vendortype )
				addfield organizationTypes[0]
				orgtypefield="${field}"
			;;
			phone | phone1 | phonenum | phonenumber | preferredphonenumber | tel | telephone )
				addfield phoneNumbers[${phone_iter}].phoneNumber
				addvalue phoneNumbers[${phone_iter}].type Office
				addvalue phoneNumbers[${phone_iter}].isPrimary true
				phone_iter=$(($note_iter + 1))
				phonecategoryfield="${field}"
			;;
			fax | phone2 | phonenum2 | phonenumber2 | tel2 | telephone2 )
				addfield phoneNumbers[${phone_iter}].phoneNumber
				addvalue phoneNumbers[${phone_iter}].type Office
				addvalue phoneNumbers[${phone_iter}].isPrimary false
				phone_iter=$(($note_iter + 1))
			;;
			orgstatus | orgstatusactiveinactivepending | status )
				addreplacerules status '"active":"Active","ACTIVE":"Active","inactive":"Inactive","INACTIVE":"Inactive","pending":"Pending","PENDING":"Pending"'
			;;
		esac
	done
	[[ -z ${addresscategoryfield} ]] && echo -e "${addressfield}\tfolio_value\n*\tOffice" > address_categories.tsv

	[[ -n ${codefield} ]] && echo -e "${codefield}\tfolio_code\n" > organizationCodeMap.tsv
	[[ -n ${orgtypefield} ]] && echo -e "${orgtypefield}\tfolio_name\n*\tOffice" > organization_types.tsv
	[[ -n ${addresscategoryfield} ]] && echo -e "${addresscategoryfield}\tfolio_value\n*\tOffice" > address_categories.tsv
	[[ -n ${emailcategoryfield} ]] && echo -e "${emailcategoryfield}\tfolio_value\n*\tOffice" > email_categories.tsv
	[[ -n ${phonecategoryfield} ]] && echo -e "${phonecategoryfield}\tfolio_value\n*\tOffice" > phone_categories.tsv
}

build_user_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			id | patronuniqueid | primaryidentifier | record | recordnumberpatron | uniqueid | userid | useruserid )
				addfield legacyIdentifier
				idfield="${field}"
				;;
			categorycode | group | mappedpatrongroup | patronborrowercategory | patrongroup | patrongroupcode | patrontype | ptype | ptypecode | type | usergroup | usergroupcode | userprofile )
				addfield patronGroup
				groupfield="${field}"
			;;
			note | notes | note_content | notepatron | patronnote | patronnotes | borrowernote |userxinfonote | comment )
				addfield notes[${note_iter}].note
				addvalue notes[${note_iter}].noteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				note_iter=$(($note_iter + 1))
			;;
			firstname | fname | givenname | patrongivenname )
				addfield personal.firstName 
				;;
			 middle | middlename | mname )
				addfield personal.lastName 
				;;
			 familyname | lastname | lname | patronfamilyname | surname )
				addfield personal.lastName 
				lnamefield="${field}"
				;;
			address1phone1 | homephone | patronphone | patronphonenumber | phone | phoneno | phonenumber | primaryphone | telephone )
				addfield personal.phone 
				;;
			 cellphone | mobile | mobilephone )
				addfield personal.mobilePhone 
				;;
			 email | emailaddr | emailaddress | emailaddress1 | patronemail  | patronemailaddress | primaryemail )
				addfield personal.email
				addregexrules personal.email email
				;;
			loginid | username )
				addfield username
				userfield="${field}"
				;;
			 addr1 | addr1line1 | address | address1 | address1line1 | addrline1 | homeadddress1 | permaddressline1 | primaryaddress )
				addfield personal.addresses[0].addressLine1
				addvalue personal.addresses[0].addressTypeId primary
				;;
			 addr2 | addr2line1 | address2 | address2 | address2line1 | addr2line1 )
				addfield personal.addresses[1].addressLine1
				addvalue personal.addresses[1].addressTypeId work
				;;
			 addr1city | address1city | city | homecity | permcity )
				addfield personal.addresses[0].city
				;;
			 addr2city | address2city | city2 )
				addfield personal.addresses[1].city
				;;
			 addr1zip | address1zip | homezip | patronpostalcode | permzip | postalcode | zip )
				addfield personal.addresses[0].postalCode
				;;
			 addr2zip | address2zip | postalcode2 | zip2 )
				addfield personal.addresses[1].postalCode
				;;
			 addr1state | address1state | homestate | patronprovince | permstate | region | state )
				addfield personal.addresses[0].region
				;;
			 addr2state | address2state | region2 | state2 )
				addfield personal.addresses[1].region
				;;
		esac
	done

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")

		case ${comp_field} in 
			barcode | pbarcode | patronbarcode | cardnumber | borrowerid )
				if [[ -z ${idfield} ]];then
					addfield legacyIdentifier
					addfield barcode
					idfield=${field}
					barcodefield=${field}
				else
					addbackupfield barcode "${idfield}"
				fi
			;;
			patrnname | name )
				if [[ -z ${lastname} ]];then
					addfield personal.lastName
					addfield personal.firstName
				else
					addfield personal.firstName
				fi
			;;
		esac
	done

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			univid | uniid | externalsystemid | studentid )
				if [[ -z ${barcode} ]];then
					addbackupfield barcode "${idfield}"
					field=${barcodefield}
				fi	
			;;
		esac
	done
	if [[ -z ${lastname} ]];then
		[[ -n ${firstname} ]] && lastname="${firstname}"
	fi
	[[ -n ${groupfield} ]] && echo -e "${groupfield}\tfolio_group\n*\tmigration" > user_groups.tsv
}
initialize

case ${filetype} in	
	composite_order)
		build_order_map
		print_results
		;;
	holdings)
		build_holdings_map
		print_results
		;;
	item)
		build_item_map
		print_results
		filetype="holdings"
		initialize
		build_holdings_map
		echo
		print_results
		;;
	organization)
		build_organization_map
		print_results
		;;
	user)
		build_user_map
		print_results
		;;

esac

