#!/usr/bin/bash

while getopts "hiouv:" opt; do
  case $opt in
    h)
      filetype="holdings"
      ;;
		i) 
			filetype="item"
			;;
		o) 
			filetype="order"
			;;
		u) 
			filetype="user"
			;;
		v) 
			filetype="organization"
			;;
    \?)
      echo "Error: Invalid option -$OPTARG" >&2
      echo "Usage: $0 [-hiouv]" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

infile="${1}"

if [[ ! -f ${infile} ]] || [[ -z ${filetype} ]];then 
cat << EOF

You must supply a file name and supply a switch to indicate filetype.

File types: 
	-h: holdings
	-i: item (also builds holdings)
	-o: order
	-u: user
	-v: organizations

EOF
	exit
fi

IFS= read -r -d '' item_statuses <<'EOF'
legacy_code	folio_name
m	Missing
$	Lost and paid
o	Restricted
w	Withdrawn
p	In process
z	Claimed returned
!	Awaiting pickup
n	Aged to lost
b	In process
At Bindery	In process (non-requestable)
Claimed Returned	Claimed returned
In Process	In process
In process (non-requestable)	In process (non-requestable)
Lib Use Only	Restricted
Library use only	Restricted
Lost	Lost
Lost--System Applied	Lost
Withdrawn	Withdrawn
BINDERY In process (non-requestable)
CATALOGING  In process
CLAIMED_RETURNED  Claimed returned
DAMAGED In process (non-requestable)
DISCARD Withdrawn
DISPATCHED  In transit
INPROCESS In process
IN_PROCESSING In process
LOST  Lost and paid
LOST-ASSUM  Missing
LOST-CLAIM  Declared lost
LOST-CLAIM  Missing
LOST-PAID Lost and paid
NON-CIRC  Restricted
RESTRICTED  Restricted
WITHDRAWN Withdrawn
EOF

note_iter=0
chkinnote_iter=0
chkinnote_iter=0

### processed twice so fallback fields can be identified
IFS=$'\t' read -r -a header_arr < <(head -1 "${infile}" )

addfield() {
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\"}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addbackupfield() {
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"legacy_backupfield\":\"${2}\"}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

addvalue() {
	newfield="{\"folio_field\":\"${1}\",\"legacy_field\":\"${field}\",\"value\":\"${2}\"}"
	object_map=$(jq --argjson NEWFIELD "${newfield}" '.data += [ $NEWFIELD ]' <<< "${object_map}")
}

initialize() {
	object_map='{"data":[]}'
	outfile="${filetype}_mapping.json"
}

print_results() {
	jq '.data |= sort_by(.folio_field)' <<< "${object_map}" \
	  | sed 's/"true"/true/;s/"false"/false/' > "${outfile}"
	{
	  echo -e "Legacy field\tFOLIO field"
	  jq -r '.data[] | [.legacy_field, .folio_field] | @tsv' "${outfile}"
	} > tmpmap
	
	echo "MAPPED and UNMAPPED fields from ${infile} output to ${outfile}"
	echo "Delimited map templates have been created"
	echo
	
	jq -r '.data[].legacy_field' "${outfile}" | sort -u > tmp1
	head -1 "${infile}" | tr '\t' '\n' | sort -u > tmp2
	awk -v FS='\t' '
	  NR==FNR { seen[$1]=1; next }
	  !($1 in seen) { print $1 }
	' tmp1 tmp2 > tmpunmapped1
	
	{
	  echo "UNMAPPED legacy fields found in ${infile}"
	  cat tmpunmapped1
	} > tmpunmapped2
	
	paste -d $'\t' tmpmap tmpunmapped2 | column -t -s $'\t'
	
	rm -f tmp1 tmp2 tmpunmapped1 tmpunmapped2 tmpmap
}

build_holdings_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			bibid | bibno | mmsid | mmsrecordid | recordbiblio | recordbibliographic | recordnumberbibliographic )
				addfield instanceId
				bibfield="${field}"
				;;
			id | itemid | itempid | physicalitemid | recorditem | z30reckey)
				addfield legacyIdentifier
				itemfield="${field}"
				;;
			callitem | permanentcallnumber | shelfmark )
				addfield callNumber 
				callfield="${field}"
				;;
			holdid | holrecordid | holdingsid | mfhdid | z30holdocunumber )
				addfield holdingsRecordId 
				holdidfield="${field}"
			;;
			holdings | libhas | libhascheckin | summaryholding | summaryholdings )
				addfield holdingsStatements[0].statement
			;;
			itempermanentlocation | itemshelvinglocation | permanentlocation | permanentphysicallocation )
				addfield permanentLocationId
				locationfield="${field}"
			;;
		esac
	done

	

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			call | callmarc | callno | callnumber )
				if [[ -z ${callfield} ]];then
					callfield=${field}
					addfield callNumber
				fi	
			;;
			callprefix | callnumberprefix )
				addfield callNumberPrefix
			;;
			callsuffix | callnumbersuffix )
				addfield callNumberPrefix
			;;
			oclc | oclcnumber )
				if [[ -z ${bibfield} ]];then
					bibfield=${field}
					addfield instanceId
				fi	
			;;
			loc | location )
				if [[ -z ${locationfield} ]];then
					addfield permanentLocationId
					locationfield=${field}
				fi	
			;;
		esac
	done

	# extra sweep to pull up bib specific call numbers

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			bibcall | callbiblio | callbibliographic | callnonmarc )
				if [[ -z ${callfield} ]];then
					callfield=${field}
					addfield callNumber
				fi	
			;;
		esac
	done

	if [[ -z ${holdidfield} ]];then
		field=${itemfield}
		addfield holdingsRecordId
	fi

	[[ -n ${typefield} ]] && echo -e "${mattypefield}\tfolio_name\n*\tmigration" > material_types.tsv
	[[ -n ${locationfield} ]] && echo -e "${locationfield}\tlegacy_code\tfolio_code\n*\t*\tmigration" > locations.tsv
}

build_item_map() {
	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			id | itemid | itempid | physicalitemid | recorditem | z30reckey)
				addfield legacyIdentifier
				itemfield="${field}"
				;;
			barcode | itembarcode | z30barcode )
				addfield barcode
				barcodefield="${field}"
			;;
			holdid | holrecordid | holdingsid | mfhdid | z30holdocunumber )
				addfield holdingsRecordId 
				holdidfield="${field}"
			;;
			materialformat | materialtype | mattype | mtype | mediaitm | z30material )
				addfield materialTypeId 
				mattypefield="${field}"
			;;
			loantype | itempolicy )
				addfield permanentLoanTypeId 
				loantypefield="${field}"
			;;
			fulfillmentnote | imessage | imsg | messgage | checkinnote )
				addfield circulationNotes[0].note
				addvalue circulationNotes[0].noteType "Check in"
				addvalue circulationNotes[0].staffOnly true
			;;
			internalnote | intnote | staffnote )
				addfield notes[${note_iter}].note
				addvalue notes[${note_iter}].itemNoteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				addvalue notes[${note_iter}].staffOnly true
				note_iter=$(($note_iter + 1))
			;;
			note | opacmsg |publicnote | z30noteopac )
				addfield notes[${note_iter}].note
				addvalue notes[${note_iter}].noteTypeId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
				addvalue notes[${note_iter}].staffOnly false
				note_iter=$(($note_iter + 1))
			;;
			copy | copynumber | copyno | copyid | z30copyid | itemcopyid )
				addfield copyNumber
			;;
			chron | chronology )
				addfield volume
			;;
			enum | enumeration | itemenum )
				addfield enumeration
			;;
			vol | volume )
				addfield volume
			;;
			year )
				addfield yearCaption[0]
			;;
			pieces)
				addfield numberOfPieces 
			;;
			itemstatus | itemstatusdesc | itemstatuscurrentstatus | status | statusmappingkey )
				addfield status.name
				statusfield="${field}"
			;;
			templocation | itemtemporaryshelvinglocation)
				addfield temporaryLocationId
			;;
		esac
	done

	

	for field in "${header_arr[@]}"; do
		comp_field=$(tr -dc "[a-z0-9]" <<< "${field,,}")
	
		case ${comp_field} in 
			barcode | itembarcode | z30barcode )
				if [[ -z ${itemfield} ]];then
					addfield legacyIdentifier
					field=${itemfield}
					addfield barcode
				else
					addbackupfield barcode "${itemfield}"
				fi	
			;;
			itype | itemtypeid | itemtypecode )
				if [[ -z ${mattypefield} ]];then
					addfield materialTypeId
					mattypefield="${field}"
				fi
				if [[ -z ${loantypefield} ]];then
					addfield permanentLoanTypeId
					loantypefield="${field}"
				fi
			;;
		esac
	done

	if [[ -z ${holdidfield} ]];then
		field=${itemfield}
		addfield holdingsRecordId
	fi

	[[ -n ${mattypefield} ]] && echo -e "${mattypefield}\tfolio_name\n*\tmigration" > material_types.tsv
	[[ -n ${loantypefield} ]] && echo -e "${loantypefield}\tfolio_name\n*\tmigration" > loan_types.tsv
	echo -e "${item_statuses}" > item_statuses.tsv
}

initialize

case ${filetype} in	
	holdings)
		build_holdings_map
		print_results
		;;
	item)
		build_item_map
		print_results
		filetype="holdings"
		initialize
		build_holdings_map
		echo
		print_results
		;;

esac

