#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

if [[ ${1} =~ ^[0-9][0-9][0-9]$ ]];then
	tag=${1}
else
	echo "Please enter a numeric MARC tag"
	echo "At the time this was written, only 008 is supported"
	exit
fi

curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/marc-specifications/bibliographic/${tag}"



