#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

if [[ ${1} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
	uuid=${1}
else
	echo "You must enter a valid UUID. To list all specifications uuids, use marcspecs-get"
	exit
	echo
fi

curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/specification-storage/specifications/${uuid}?include=all" |jq . |tee marcspec.json

echo 
echo "Output has been sent to marcspec.json"
echo


