#!/usr/bin/awk -f

BEGIN{

outfile="outfile"
idfield="001"

	print "id\tfield" > outfile 
	RS=ORS="\n\n";FS="\n"
}

function extract_data(){
	ORS=""

	id=value1=""

	for(i=1; i<=NF; i++) {
		if(substr($i, 2, 3) == idfield) {
			id = substr($i, 7)
		}

		if(substr($i, 2, 3) == "994") {
			split($i, subfields, "$")

			for (j in subfields) {
				if (substr(subfields[j], 1, 1) == "b") {
					value1 = substr(subfields[j], 2)
					print id"\t"value1"\n" >> outfile 
				}
			}

		}

	}
	
}

{

ORS="\n\n"

extract_data()

if(NR % 10000 == 0 ) {printf ("Processed %d records\r", NR)}
}

