#!/usr/bin/awk -f

# for multivalued fields that need separate lines, the print routine needs to be moved or refactored

BEGIN{

	delimiter=";"
	
	# load command line arguments into fields/subfields, expects 110a, 245c, etc
	numfields=ARGC - 1

	for(i = 1; i < numfields; i++) {
                field[i]=substr(ARGV[i],1,3)
		subfield[i]=substr(ARGV[i],4,1)
		delete ARGV[i]
	}
	
	header=""
	for (k = 1;k <= numfields; k++) { header=header"\t"field[k]""subfield[k] }
	print "id"header 
	RS=ORS="\n\n";FS="\n"
}

function extract_subfield() {
	split($i, subfields, "$")

	for (j in subfields) {
		if (substr(subfields[j], 1, 1) == subfield[k]) {
			if (value[k] == "") {
				value[k] = substr(subfields[j], 2)
			} else { 
				value[k] = value[k]""delimiter""substr(subfields[j], 2)
			}
		}
	}
}

function extract_data(){
	ORS=""

	id=""

	#extact 001 as ID, use 907a if found
	for(i=1; i<=NF; i++) {
		if(substr($i, 2, 3) == "001") { id = substr($i, 7) } 
			
		if(substr($i, 2, 3) == "907") {
			split($i, subfields, "$")

			for (j in subfields) {
				if (substr(subfields[j], 1, 1) == "a") { id = substr(subfields[j], 2) }
			}
		}

		for (k = 1;k <= numfields; k++) {
			if(substr($i, 2, 3) == field[k]) {
				extract_subfield()
			}	
		}

	}
	lineout=""
	for (k in field) { 
		lineout=lineout"\t"value[k]
		value[k]="" 
	}

	print id""lineout"\n" 
	
}

{

ORS="\n\n"

extract_data()

if(NR % 10000 == 0 ) {printf ("Processed %d records\r", NR)}
}

