#!/usr/bin/awk -f

BEGIN{

outfile="outfile"

idfield="001"
idsubfield=""

field[0]="852"
subfield[0]="i"

	print "id\tfield" > outfile 
	RS=ORS="\n\n";FS="\n"
}

function extract_subfield() {
	split($i, subfields, "$")

	for (j in subfields) {
		if (substr(subfields[j], 1, 1) == subfield[k]) {
			value[k] = substr(subfields[j], 2)
		}
	}
}

function extract_data(){
	ORS=""

	id=value1=""

	#extract field depending if in control or variable field
	for(i=1; i<=NF; i++) {
		if(substr($i, 2, 3) == idfield) {
			if (idsubfield == ""){
				id = substr($i, 7)
			} else {
				split($i, subfields, "$")

				for (j in subfields) {
					if (substr(subfields[j], 1, 1) == idsubfield) {
						id = substr(subfields[j], 2)
					}
				}
			}
		}

		for (k in field) {
			if(substr($i, 2, 3) == field[k]) {
				extract_subfield()
			}	
		}

	}
	lineout=""
	for (k in field) {
		lineout=lineout"\t"value[k]
	}

	print id""lineout"\n" >> outfile 
	
}

{

ORS="\n\n"

extract_data()

if(NR % 10000 == 0 ) {printf ("Processed %d records\r", NR)}
}

