#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# Creates materialtypes based on contents of single column file named mattypes containing material types
#

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

infile=mattypes.tsv

if [[ ! -f ${infile} ]];then echo "Expected file ${infile} not found";exit;fi

while read materialtype
do

materialtype=${materialtype/^ *//}
materialtype=${materialtype/ *$//}
materialtype=$(jq -aR . <<< ${materialtype})

uuid=$(uuidgen)

IFS='' read -r -d '' materialtype << EndOfMaterialType
{
"id": "${uuid}",
"name": ${materialtype},
"source": "local"
}
EndOfMaterialType


apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${materialtype}" "${okapi_url}/material-types")

echo -e "${apicall}" |jq '.'

done < ${infile}


