#!/usr/bin/bash

file1="${1}"
file2="${2}"
outfile="merged_file.tsv"

if [[ ! -f "${file1}" ]] || [[  ! -f "${file2}" ]];then
	echo "You must enter two tab delimited files to be combined"
	exit
fi

awk -F'\t' '
NR==FNR {
    if (FNR == 1) {
        for (i=1; i<=NF; i++) {
            if (!($i in col_index)) {
                col_index[$i] = ++ncols
                cols[ncols] = $i
            }
            f1_map[$i] = i
        }
        next
    }

    # store rows
    for (i=1; i<=NF; i++) {
        f1[FNR,i] = $i
    }
    f1_rows = FNR
    next
}

FNR == 1 {
    for (i=1; i<=NF; i++) {
        if (!($i in col_index)) {
            col_index[$i] = ++ncols
            cols[ncols] = $i
        }
        f2_map[$i] = i
    }

    for (i=1; i<=ncols; i++) {
        printf "%s%s", cols[i], (i==ncols ? ORS : OFS)
    }

    for (r=2; r<=f1_rows; r++) {
        for (i=1; i<=ncols; i++) {
            col = cols[i]
            if (col in f1_map)
                val = f1[r, f1_map[col]]
            else
                val = ""
            printf "%s%s", val, (i==ncols ? ORS : OFS)
        }
    }
    next
}

{
    for (i=1; i<=ncols; i++) {
        col = cols[i]
        if (col in f2_map)
            val = $f2_map[col]
        else
            val = ""
        printf "%s%s", val, (i==ncols ? ORS : OFS)
    }
}
' OFS='\t' "${file1}" "${file2}" > ${outfile}

echo "A file containing the combined headers from ${file1} and ${file2} was output to ${outfile}"
echo
