#!/usr/bin/awk -f
#


BEGIN{FS="\t"}

{
	bibId=$1
	holdId=$2
	callNum=$3
	callPrefix=""
	libHas=$4
	actionNote=$5 # intlNote
	note=$6
	location=$7
	ownershipNote=""
	bindingNote=""
	reproductionNote=""
	termsOfUse=""
	url=""

	sub(/ /,"$i",callNum)
	if (location == "") {location = "migration"}

	mfhd = "=LDR  00155cx   22000733  4500\n=001  "holdId"\n=004  "bibId"\n=008  9810090p\\\\\\\\8\\\\\\4001aueng0000000\n"

	if (note != "") { 
	        split(note, notes, ";")
                for (n in notes)
                        mfhd = mfhd"=538  \\\\$i"notes[n]"\n"
	}
	if (ownershipNote != "") { 
		mfhd = mfhd"=561  0\\$a"ownershipNote"\n"
	}
	if (bindingNote != "") { 
		mfhd = mfhd"=563  \\\\$x"bindingNote"\n"
	}
	if (ac3yytionNote != "") { 
		mfhd = mfhd"=583  \\\\$x"actionNote"\n"
	}

	if (callPrefix != "") { 
		callPrefix="$k"callPrefix
	}

	mfhd = mfhd"=852  0\\$b"location""callPrefix"$h"callNum"\n"

	if (url != "") { 
		mfhd = mfhd"=856  \\\\$u"url"\n"
	}

	if (libHas != "") { 
		split(libHas, statements, ";")
		for (statement in statements)
			mfhd = mfhd"=866  \\\\$a"statements[statement]"\n"
	}


	mfhds[holdId] = mfhd
}

END { 
	for (record in mfhds ) { 
		print mfhds[record] > "mfhds.mrk"
		counter++
	}
	print NR " item records processed to create  " counter " MFHDs" 
} 


