#!/usr/bin/awk -f
#


BEGIN{FS="\t"}
function checkdigit(num) 
{
	gsub(/;.*$/, "", num)
	gsub(/[^0-9]/, "", num)

	m = 2
	x = 0
	i = num
	while (i > 0) {
		a = i % 10
		i = int(i/10)
		x += a * m
		m += 1
		}
	r = x % 11
	if (r == 10) {r = "x"}	
	return ".b"num""r
}

{

if (NR == 1) {
	for(i=1;i<=NF;i++) {
		switch($i) {
			case "bibIds":
				bibId = i
				break
			case "CALL_#":
				callNum = i
				break
			case "LOCATION":
				location = i
				break
			case "LIBHAS(HoldingsStatement)":
				libHas = i
				break
			case "SCODE4":
				ownershipNote = i
				break
			case "NOTE":
				note = i
				break
			case "INT_NOTE":
				actionNote = i
				break
			case "MESSAGE":
				actionNote2 = i
				break
			}
		}
	}


### Only process if attached to a bib
if ($bibId != "") {
	$bibId=checkdigit($bibId)
	callPrefix=""
	note2=""
	copyNote=""
	ownershipNote2=""
	bindingNote=""
	bindingNote2=""
	reproductionNote=""
	termsOfUse=""
	url=""

	if (location ~ /[a-zA-Z0-9]/) holdId = $bibId""$location
	gsub(/;.*/, "", $callNum)

	sub(/ /,"$i",$callNum)
	if ($location == "") $location = "migration"

	mfhd = "=LDR  00155cx   22000733  4500\n=001  "holdId"\n=004  "$bibId"\n=008  9810090p\\\\\\\\8\\\\\\4001aueng0000000\n"

	if (note != "") { 
                split($note, notes, ";")
		for (n in notes)
			mfhd = mfhd"=538  \\\\$i"notes[n]"\n"
	}
	if (note2 != "") { 
                split(note2, notes, ";")
		for (n in notes)
			mfhd = mfhd"=538  \\\\$i"notes[n]"\n"
	}
	if (ownershipNote != "") { 
		mfhd = mfhd"=561  0\\$a"$ownershipNote"\n"
	}
	if (ownershipNote2 != "") { 
		mfhd = mfhd"=561  0\\$a"ownershipNote2"\n"
	}
        if (copyNote != "") {
		mfhd = mfhd"=562  0\\$a"$copyNote"\n"
 	}
	if (bindingNote != "") { 
		mfhd = mfhd"=563  \\\\$x"$bindingNote"\n"
	}
	if (bindingNote2 != "") { 
		mfhd = mfhd"=563  \\\\$x"$bindingNote2"\n"
	}
	if ($actionNote != "") { 
		split($actionNote, statements, ";")
		for (statement in statements)
			mfhd = mfhd"=583  \\\\$x"statements[statement]"\n"
	}
	if ($actionNote2 != "") { 
		split($actionNote2, statements, ";")
		for (statement in statements)
			mfhd = mfhd"=583  \\\\$x"statements[statement]"\n"
	}
	if (callPrefix != "") { 
		$callPrefix="$k"$callPrefix
	}

	mfhd = mfhd"=852  0\\$b"$location"$h"$callNum"\n"

	if (url != "") { 
		mfhd = mfhd"=856  \\\\$u"$url"\n"
	}

	if ($libHas != "") { 
		split($libHas, statements, ";")
		for (statement in statements)
			mfhd = mfhd"=866  \\\\$a"statements[statement]"\n"
	}


	print mfhd > "mfhds_fromcheckins.mrk"
	if(NR % 10000 == 0 ) {printf ("%d checkin records processed\r", NR) }
	}
}

END { 
	print NR " checkin records processed" 
} 


