#!/usr/bin/awk -f
#


BEGIN{FS="\t"}
function checkdigit(num) 
{
	gsub(/;.*$/, "", num)
	gsub(/[^0-9]/, "", num)

	m = 2
	x = 0
	i = num
	while (i > 0) {
		a = i % 10
		i = int(i/10)
		x += a * m
		m += 1
		}
	r = x % 11
	if (r == 10) {r = "x"}	
	return ".b"num""r
}

{

	bibId=checkdigit($3)
	holdId=$1
	callNum=$23
	callPrefix=""
	libHas=$21
	actionNote=$25
	actionNote2=$27
	note=$24
	note2=""
	copyNote=""
	location=$11
	ownershipNote="$15"
	ownershipNote2=""
	bindingNote=""
	bindingNote2=""
	reproductionNote=""
	termsOfUse=""
	url=""

	if (location ~ /[a-zA-Z0-9]/) holdId = bibId""location
	gsub(/;.*/, "", callNum)

	sub(/ /,"$i",callNum)
	if (location == "") location = "migration"

	mfhd = "=LDR  00155cx   22000733  4500\n=001  "holdId"\n=004  "bibId"\n=008  9810090p\\\\\\\\8\\\\\\4001aueng0000000\n"

	if (note != "") { 
                split(note, notes, ";")
		for (n in notes)
			mfhd = mfhd"=538  \\\\$i"notes[n]"\n"
	}
	if (note2 != "") { 
                split(note2, notes, ";")
		for (n in notes)
			mfhd = mfhd"=538  \\\\$i"notes[n]"\n"
	}
	if (ownershipNote != "") { 
		mfhd = mfhd"=561  0\\$a"ownershipNote"\n"
	}
	if (ownershipNote2 != "") { 
		mfhd = mfhd"=561  0\\$a"ownershipNote2"\n"
	}
        if (copyNote != "") {
		mfhd = mfhd"=562  0\\$a"copyNote"\n"
 	}
	if (bindingNote != "") { 
		mfhd = mfhd"=563  \\\\$x"bindingNote"\n"
	}
	if (bindingNote2 != "") { 
		mfhd = mfhd"=563  \\\\$x"bindingNote2"\n"
	}
	if (actionNote != "") { 
		mfhd = mfhd"=583  \\\\$x"actionNote"\n"
	}
	if (actionNote2 != "") { 
		mfhd = mfhd"=583  \\\\$x"actionNote2"\n"
	}
	if (callPrefix != "") { 
		callPrefix="$k"callPrefix
	}

	mfhd = mfhd"=852  0\\$b"location""callPrefix"$h"callNum"\n"

	if (url != "") { 
		mfhd = mfhd"=856  \\\\$u"url"\n"
	}

	if (libHas != "") { 
		split(libHas, statements, ";")
		for (statement in statements)
			mfhd = mfhd"=866  \\\\$a"statements[statement]"\n"
	}


	print mfhd > "mfhds.mrk"
	if(NR % 10000 == 0 ) {printf ("%d checkin records processed\r", NR) }
}

END { 
	print NR " checkin records processed" 
} 


