#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)
edge_key=$(cat edge.key)
tenant=$(cat tenant)
edge_url=$(cat okapi.url |sed 's/okapi-/edge-/')
oai_server="${edge_url}/oai/$(cat edge.key)?verb=ListRecords"

if [[ ! $(which yaz-marcdump |grep yaz) ]];then
	echo
	echo "You must install yaz to use this utility"
	echo "sudo apt install yaz libyaz5"
	echo
	exit
fi

#### look for single record query and exit
search=$(echo ${1} |tr "." "-" |tr -dc [^a-z0-9\-])

if [[ ${1} == "full" ]];then
	fullharvest="yes"
	metadataprefix="marc21"
else
	metadataprefix="marc21_withholdings"
fi

if [[ ${1} =~ ^[12][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$ ]];then
	from=$(date -u -d "${1}" +"%Y-%m-%dT%H:%M:%SZ")
else
	from=$(date -u -d '1 hour ago' +"%Y-%m-%dT%H:%M:%SZ")
fi

if [[ ${search} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
        instance_uuid=${search}
elif [[ ${search} =~ ^in[0-9a]*$ ]];then
        instance_uuid=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/instance-storage/instances?query=hrid==${search}" |jq -r '.instances[].id')
fi

if [[ ${instance_uuid} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then

        oai_prefix=$(curl -s -X GET "${edge_url}/oai/${edge_key}?verb=Identify" | sed 's/.*<oai-identifier:repositoryIdentifier>\([^<]*\).*/\1/')

        apicall=$(curl -s -X GET "${edge_url}/oai/${edge_key}?verb=GetRecord&identifier=oai:${oai_prefix}:${tenant}/${instance_uuid}&metadataPrefix=${metadataprefix}")

        echo "${apicall}" |xmlstarlet fo
        echo "${edge_url}/oai/${edge_key}?verb=GetRecord&identifier=oai:${oai_prefix}:${tenant}/${instance_uuid}&metadataPrefix=${metadataprefix}"
        exit
fi

from='&from='${from}
[[ ${fullharvest} == "yes" ]] && from=""

echo "${oai_server}&metadataPrefix=${metadataprefix}${from}"

resumption_token=''
counter=0
SECONDS=0

read -r -d '' stylesheet <<'EOF'
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
    xmlns:oai="http://www.openarchives.org/OAI/2.0/"
    xmlns:marc="http://www.loc.gov/MARC21/slim"
    exclude-result-prefixes="oai">
  <xsl:output method="xml" indent="yes"/>
  <xsl:template match="/">
    <collection xmlns="http://www.loc.gov/MARC21/slim">
      <xsl:apply-templates select="//marc:record"/>
    </collection>
  </xsl:template>
  <xsl:template match="marc:record">
    <xsl:copy-of select="."/>
  </xsl:template>
</xsl:stylesheet>
EOF

if [[ ${resumption_token} == '' ]]; then
        rm -rf oaiharvest
        mkdir oaiharvest

        oai_data=$(curl -s --retry 9 --retry-delay 300 "${oai_server}&metadataPrefix=${metadataprefix}${from}")
				yaz-marcdump -i marcxml -o marc <(xmlstarlet tr <(echo "${stylesheet}") <(echo "${oai_data}")) > oaiharvest/${counter}.mrc


        counter=$((${counter} + 1))

        resumption_token=$((grep -o '<resumptionToken.*</resumptionToken>' |grep -oi '>[a-z0-9]*<' |tr -d '<>') <<<  "${oai_data}")
fi


while [[ ${resumption_token} != '' ]]; do
	oai_data=$(curl -s --retry 9 --retry-delay 60 "${oai_server}&resumptionToken=${resumption_token}")
	resumption_token=$((grep -o '<resumptionToken.*</resumptionToken>' |grep -oi '>[a-z0-9]*<' |tr -d '<>') <<<  "${oai_data}")
	yaz-marcdump -i marcxml -o marc <(xmlstarlet tr <(echo "${stylesheet}") <(echo "${oai_data}")) > oaiharvest/${counter}.mrc
	counter=$((${counter} + 1))

	echo -en "$(( $counter )) tokens processed in $SECONDS seconds\r"
done

echo "$(( $counter )) tokens processed in $SECONDS seconds"

