#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

declare -A organization_dict

filename="org_phone.tsv"

numrecs=$(wc -l ${filename} |cut -d " " -f1)

counter=0

while IFS=$'\n' read line;do
	line=$(echo "${line}" | tr -d '"' | tr "\t" "^")
	IFS='^' read -r code phone type categories <<< ${line}

	organization=$(curl -G -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" --data-urlencode "query=code=${code}" "${okapi_url}/organizations/organizations") 


	if [[ "${organization}" =~ [0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]* ]];then
		if [[ $categories =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f] ]];then
			categories=$(sed 's/^/"/' <<< $categories)
			categories=$(sed 's/$/"/' <<< $categories)
			categories=$(sed 's/,/","/g' <<< $categories)
		fi
	
		phone="{ \"phoneNumber\" : \"${phone}\", \"type\": \"${type}\", \"isPrimary\" : false, \"categories\" : [${categories}] }"	

		updated_org=$(echo "${organization}" |jq --argjson PHONE "${phone}" '.organizations[] | del(.metadata) | .phoneNumbers += [ $PHONE ]')
		uuid=$(echo "${updated_org}" |jq -r .id)
        fi
	apicall=$(curl --http1.1 -s -w '\n' -X PUT -H "Content-type: application/json" -H "Accept: text/plain" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${updated_org}" ${okapi_url}/organizations-storage/organizations/${uuid})

	counter=$((counter + 1))
	echo "Processing $code -- record $counter of $numrecs"
	echo "${apicall}"
done < ${filename}

