#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

username=$(sed 's/[^0-9a-z\-]//gi' <<< "$1")
password=$2

apicall=$(curl -s -w '\n' -X GET -D \
  -H "Accept: application/json" \
  -H "X-Okapi-Tenant: ${tenant}" \
  -H "x-okapi-token: ${okapi_token}" \
  "${okapi_url}/users?query=username=${username}")

user_uuid=$(echo $apicall |jq -r '.users[0].id')

apicall=$(curl -s -w '\n' -X GET -D \
  -H "Accept: application/json" \
  -H "X-Okapi-Tenant: ${tenant}" \
  -H "x-okapi-token: ${okapi_token}" \
  "${okapi_url}/authn/credentials-existence?userId=${user_uuid}")

credsexist=$(echo "${apicall}" |jq -r .credentialsExist) 

if [[ ${credsexist} == "true" ]];then
	apicall=$(curl -s -w '\n' -X DELETE -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/authn/credentials?userId=${user_uuid}")
	echo $apicall
fi

data="{\"username\":\"${username}\",\"password\":\"${password}\",\"userId\":\"${user_uuid}\",\"id\":\"$(uuidgen)\"}"

apicall=$(curl --http1.1 -s -w '\n' -X POST \
	-H "Content-type: application/json" \
	-H "Accept: application/json" \
	-H "X-Okapi-Tenant: ${tenant}" \
	-H "x-okapi-token: ${okapi_token}" \
	-d "${data}" \
	"${okapi_url}/authn/credentials")
echo $apicall
