#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# list available permissions and subpermissions. Usage: ./permissions-list

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

set="${1}"

apicall=$(curl -s -w '\n' -X GET -D \
  -H "Accept: application/json" \
  -H "X-Okapi-Tenant: ${tenant}" \
  -H "x-okapi-token: ${okapi_token}" \
  "${okapi_url}/perms/permissions?expandSubs=true&query=(mutable==true)&length=100000")

echo "${apicall}" |jq -r --arg SET "${set}" '.permissions[] |select(.permissionName==$SET) |.subPermissions[].permissionName' |sort
