#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)
rm -f role_uuids uuids users_tmp role_users.tsv

declare -A role_dict
declare -A user_dict

eval "$(jq -r '. |@sh "role_dict[\(.id|tostring)]=\(.name|tostring)"' roles.json)"

records-get roles
jq -r .id roles.json > role_uuids

while IFS= read -r role;do
	apicall=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/roles/users?limit=5000&query=roleId==${role}")

	role_name=${role_dict[${role}]}
	echo "Processing ${role_name}"
	assigned_users=$(echo "${apicall}" |jq -r '[.userRoles[]|.userId]|join(", ")')
	echo "${assigned_users}" |tr -d ',' |tr ' ' '\n' >> users_tmp

	echo -e "${role_name}\t${assigned_users}" >> role_users.tsv
done < role_uuids

sort -u users_tmp |grep [a-f0-9] > uuids
rm users_tmp

records-getfromfile users
jq -r '"s/" + .id + "/" + .username + "/g"' users.json > users.sed
pv role_users.tsv |sed -f users.sed |sort -f > final.tsv
mv final.tsv role_users.tsv
rm users.sed
