#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
SECONDS=1
TIMER=0

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

infile="${1}.json"
recordtype=$1
operation=${2^^}
batchsize=10

outfile="${recordtype}_posting.log"
rm -f "${outfile}"

echo "This script expects input file \"${infile}\" to exist and takes two positional arguments:"
echo "1: recordtype"
echo "2: operation (POST or PUT)"
echo
echo "If operation is not supplied, script will use PUT if _version is detected in data file and POST if it is not"

if [[ ! -f ${infile} ]]; then echo "This script cannot find input file ${infile}";exit;fi
if [[ $# -eq 0 ]]; then echo "You must enter a record type";exit;fi


if [[ -z $2 ]];then 
	head ${infile} > tmp_postput
	echo "No POST or PUT directive given. Autodetecting"
	echo
	grep -q _version tmp_postput && versionfound="yes"
	if [[ versionfound == "yes" ]];then 
		echo "Version detected. Updating records with HTTP PUT"
		operation="PUT"
	else
		echo "No version detected. Creating records with HTTP POST"
		operation="POST"
	fi
	rm tmp_postput
fi



numrecs=$(wc -l ${infile} |cut -d " " -f1)

postrecord() {
	local record="${1}"
	local seq="${2}"
	local apicall

	if [[ ${operation} == "POST" ]];then
		apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "Accept: text/plain" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${record}" "${okapi_url}/${recordtype}")
	else
		id=$(echo "${record}" |jq -r .id)

		apicall=$(curl --http1.1 -s -w '\n' -X PUT -H "Content-type: application/json" -H "Accept: text/plain" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${record}" "${okapi_url}/${recordtype}/${id}")
	fi
	
	echo "${apicall}" | tr -d '\n' |sed 's/$/\n/' > "tmp_records.${seq}"

}


case $recordtype in
"accounts")
	recordtype="accounts";;
"agreements")
	recordtype="erm/sas";;
"agreements-picklists")
	recordtype="erm/refdata";;
"authorities")
	recordtype="authority-storage/authorities";;
"authorities-source")
	recordtype="authority-source-files";;
"boundwiths")
	recordtype="inventory-storage/bound-with-parts";;
"budgets")
	recordtype="finance/budgets";;
"campuses")
	recordtype="location-units/campuses";;
"composite-orders")
	recordtype="orders/composite-orders";;
"departments")
	recordtype="departments";;
"groups")
	recordtype="groups";;
"feefineactions")
        recordtype="feefineactions"
        ;;
"fines")
        recordtype="feefineactions";;
"fiscalyears")
        recordtype="finance/fiscal-years";;
"funds")
        recordtype="finance/funds";;
"holdings")
	recordtype="holdings-storage/holdings";;
"identifiertypes")
	recordtype="identifier-types";;
"instances")
	recordtype="instance-storage/instances";;
"instance-formats")
	recordtype="instance-formats";;
"instance-note-types")
	recordtype="instance-note-types";;
"instance-types")
	recordtype="instance-types";;
"interfaces")
	recordtype="organizations-storage/interfaces";;
"invoices")
	recordtype="invoice/invoices";;
"invoice-lines")
	recordtype="invoice/invoice-lines";;
"items")
	recordtype="item-storage/items";;
"libraries")
	recordtype="location-units/libraries";;
"licenses")
	recordtype="licenses/licenses";;
"licenses-picklists")
	recordtype="licenses/refdata";;
"licenses-terms")
	recordtype="licenses/custprops";;
"loans")
	recordtype="loan-storage/loans";;
"loantypes")
	recordtype="loan-types";;
"locations")
	recordtype="locations";;
"manualblocks")
	recordtype="manualblocks";;
"mattypes")
	recordtype="material-types";;
"nature-of-content")
	recordtype="nature-of-content-terms";;
"notices")
	recordtype="scheduled-notice-storage/scheduled-notices";;
"orderlines")
	recordtype="orders/order-lines";;
"organizations")
	recordtype="organizations/organizations";;
"orders")
	recordtype="orders-storage/purchase-orders";;
"parsedrecords")
	recordtype="change-manager/parsedRecords";;
"permissions")
	recordtype="perms/permissions";;
"polines")
	recordtype="orders-storage/po-lines";;
"precedingsucceeding")
	recordtype="preceding-succeeding-titles";;
"requests")
	recordtype="circulation/requests";;
"servicepoints")
	recordtype="service-points";;
"srs")
        recordtype="source-storage/records"
        ;;
"tags")
	recordtype="tags";;
"templates")
	recordtype="templates";;
"users")
	recordtype="users";;
*)
	echo "Record type '${recordtype}' not found. Supported types are accounts, agreements, agreements-picklists, authorities, authorities-source, boundwiths, campuses, composite-orders, groups, feefineactions, fiscalyears, funds, holdings, identifiertypes, instances, instance-formats, instance-note-types, instance-types, interfaces, invoices, invoice-lines, items, libraries, licenses, licenses-picklists, licenses-terms, loans, locations, manualblocks, mattypes, nature-of-content, notices, orderlines, organizations, parsedrecords, permissions, polines, precedingsucceeding, requests, servicepoints, srs, tags, templates, users."
	exit;;
esac

counter=0
seconds=1

while mapfile -t -n ${batchsize} lines && ((${#lines[@]})); do
	seq=0

	for line in "${lines[@]}";do

		postrecord "${line}" "${seq}" & 

		counter=$(($counter + 1))
		seq=$(($seq + 1))
	done
	wait

        if [[ $SECONDS -gt 500 ]]; then
								TIMER=$(($TIMER + $SECONDS))
                auth 2>/dev/null || authn 2>/dev/null
								okapi_token=$(cat okapi.token)
                SECONDS=1
        fi
				if [[ $TIMER -eq 0 ]];then TIMER=$SECONDS;fi

        TIME=$TIMER;msg="$TIMER seconds"
        if [[ $TIMER -gt 60 ]];then TIME=$(bc <<< "scale=1;$TIMER/60");msg="$TIME minutes";fi
        if [[ $TIMER -gt 3600 ]];then TIME=$(bc <<< "scale=1;$TIMER/3600");msg="$TIME hours     ";fi

	echo -en "Processing record $counter of $numrecs in $msg\r"

	cat tmp_records.* >> ${outfile}
	rm tmp_records.*

done < ${infile}

echo "Finished processing $numrecs ${recordtype} records."
echo "API output has been sent to ${outfile}"

