#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null

SECONDS=1
TIMEROFFSET=0
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

delete_metadata="yes"

if [[ -z ${1} ]];then
	echo "Usage: records-getfromfile [record_type] "
	echo
	echo "Options:"
	echo "-m Retrieve metadata (removed by default)"
	echo
	exit
fi

while getopts "m" opt; do
	case $opt in
		m)
			delete_metadata="no"
			;;
		\?)
			echo "Error: Invalid option -$OPTARG" >&2
			echo "Usage: $0 [-m]" >&2
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))

rec_type=$1
infile="uuids"
batchsize=50
accept="application/json"
sed -i 's/[^a-f0-9\-]//g' ${infile}

jq_replace=".${rec_type}[]"
queryseparator="?"

querydelim="%20or%20id=="

SECONDS=1
TIMER=1

if [[ ! -f ${infile} ]]; then echo "This script cannot find input file ${infile}";exit;fi
if [[ $# -eq 0 ]]; then echo "You must enter a record type";exit;fi

numrecs=$(wc -l ${infile} |cut -d " " -f1)

printrecords(){
	if [[ -f tmp_records.${rec_type}.0 ]];then
		if [[ ${delete_metadata} == "yes" ]]; then
			cat tmp_records.${rec_type}.* | jq -c "${jq_replace} | del(.totalRecords) |del(.resultInfo) |del(.metadata)" >>  "${rec_type}.json"
		else
			cat tmp_records.${rec_type}.* | jq -c "${jq_replace} | del(.totalRecords) |del(.resultInfo)" >>  "${rec_type}.json"
		fi
		rm -f tmp_records.${rec_type}.*
	fi
}

getbatch() {
	local querystring="${1}"
	local seq=${2}

	curl -s -w '\n' -X GET -H "Accept: ${accept}" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/${endpoint}?${querystring}&limit=${batchsize}" > tmp_records.${rec_type}.${seq}
}

getrecord() {
	local uuid=${1}
	local seq=${2}
	curl -s -w '\n' -X GET -H "Accept: ${accept}" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/${endpoint}${queryseparator}${querystring}${uuid}${poststring}" > tmp_records.${rec_type}.${seq}
}

case $rec_type in
"accounts")
	endpoint="accounts";;
"agreements")
	endpoint="erm/sas";;
"authorities")
	endpoint="authority-storage/authorities";;
"authorities-srs")
	indivrecord=1
	querystring=""
	poststring="/formatted?idType=AUTHORITY"
	queryseparator="/"
	jq_replace="."
	endpoint="source-storage/records";;
"boundwiths")
	jq_replace=".boundWithParts[]"
	endpoint="inventory-storage/bound-with-parts";;
"circlog")
	endpoint="audit-data/circulation/logs";;
"courses")
	endpoint="coursereserves/courses";;
"feefines")
	endpoint="feefines";;
"feefineactions")
	endpoint="feefineactions";;
"holdings")
	jq_replace=".holdingsRecords[]"
	endpoint="holdings-storage/holdings";;
"holdings-srs")
	endpoint="source-storage/records";;
"inhouse") 
	jq_replace=".checkIns[]"
	endpoint="check-in-storage/check-ins";;
"interfaces")
	endpoint="organizations-storage/interfaces";;
"instance-relationships")
	jq_replace=".instanceRelationships[]"
	endpoint="instance-storage/instance-relationships";;
"instances")
	endpoint="instance-storage/instances";;
"inventory")
	endpoint="inventory-view/instances"
	jq_replace=".instances[]"
	accept="text/plain";;
"items")
	endpoint="item-storage/items";;
"licenses")
	endpoint="licenses/licenses";;
"locations")
	endpoint="locations";;
"loantypes")
	endpoint="loan-types";;
"loan-history")
	endpoint="loan-storage/loan-history";;
"loans")
	endpoint="loan-storage/loans";;
"notes")
	endpoint="notes";;
"organizations")
	endpoint="organizations-storage/organizations";;
"parsedrecords")
	indivrecord=1
	querystring="externalId="
	jq_replace=".relatedRecordVersion=0"
	endpoint="change-manager/parsedRecords";;
"permissionusers")
	jq_replace=".permissionUsers[]"
	endpoint="perms/users";;
"polines")
	jq_replace=".poLines[]"
	endpoint="orders-storage/po-lines";;
"preceedingsucceeding")
	jq_replace=".precedingSucceedingTitles[]"
	endpoint="preceding-succeeding-titles";;
"requestprefs")
	jq_replace=".requestPreferences[]"
	endpoint="request-preference-storage/request-preference";;
"requests")
	endpoint="circulation/requests";;
"roles")
	endpoint="roles";;
"roleusers")
	endpoint="roles/users?limit=5000&query=roleId=="
	jq_replace=".userRoles[]"
	queryseparator=""
	indivrecord=1;;
"schedulednotices")
	endpoint="scheduled-notice-storage/scheduled-notices";;
"servicepoints")
	endpoint="service-points";;
"sharinginstances")
	jq_replace=".sharingInstances[]"
	consortiumId=$(curl -s -w '\n' -X GET -H "Accept: */*" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/consortia" |jq -r '.consortia[].id')
	endpoint="consortia/${consortiumId}/sharing/instances";;
"srs")
	indivrecord=1
	jq_replace=".sourceRecords[]"
	endpoint="source-storage/source-records"

	if [[ $2 != "srs" ]];then
		querystring="externalId="
	else
		querystring="/"
		queryseparator=""
		jq_replace="."
		endpoint="source-storage/records"
	fi
	;;
"statcodes")
	endpoint="statistical-codes";;
"tags")
	endpoint="tags";;
"userroles")
	endpoint="roles/users?limit=5000&query=userId=="
	jq_replace=".userRoles[]"
	queryseparator=""
	indivrecord=1;;
"users")
	endpoint="users";;
"vouchers")
	endpoint="voucher/vouchers";;
*)
	echo "Record type not found.";exit;;
esac

rm -f ${rec_type}.json
t=0
lastset=0

if [[ $indivrecord -eq 1 ]];then batchsize=10;fi

while mapfile -t -n ${batchsize} ids && ((${#ids[@]})); do
	counter=$(($counter + ${#ids[@]}))
	idstring="${ids[@]}"

	[[ ${#ids[@]} -lt $((${batchsize} - 1)) ]] && lastset=1
	
	if [[ $indivrecord -ne 1 ]];then
		querystring="query=id=${idstring// /${querydelim}}"
		getbatch "${querystring}" ${t} &
		t=$(($t + 1))

		if [[ $t -eq 4 || $lastset -eq 1 ]];then
			wait
			t=0
			printrecords
		fi
	else
		seq=0
		for uuid in "${ids[@]}";do
			getrecord "${uuid}" "${seq}" &
			seq=$(($seq + 1))
		done
		wait
		printrecords
	fi

    if [[ $SECONDS -gt 500 ]]; then
			TIMER=$(($TIMEROFFSET * 500 + $SECONDS))
     	auth 2>/dev/null || authn 2>/dev/null
			okapi_token=$(cat okapi.token)
      SECONDS=1
			TIMEROFFSET=$(($TIMEROFFSET + 1))
    fi

    if [[ $TIMER -lt 500 ]]; then TIMER=$SECONDS;fi

    TIME=$TIMER;msg="$TIMER seconds"

    if [[ $TIMER -gt 60 ]];then TIME=$(($TIMER/60));msg="$TIME minutes";fi
    if [[ $TIMER -gt 3600 ]];then TIME=$(($TIMER/3600));msg="$TIME hours";fi

    echo -en "Processing record $counter of $numrecs in $msg in $(($counter/$TIMER)) recs/sec          \r"

done < ${infile}

printrecords

echo "$numrecs records have been exported to \"${rec_type}.json\"                      "


