#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
# reindexes elasticsearch

tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

curl --http1.1 -s -w '\n' -X POST  -H "Accept: application/json" -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d '' "${okapi_url}/search/index/inventory/reindex/full"

