#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)


offset=0
search_for=$1
rm -rf requests

if [[ ${search_for} != "" ]];then
	if [[ ${search_for} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
		curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/circulation/requests?query=userId=${search_for}"
		exit
	else
		id=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/users?query=barcode==${search_for}"|jq -r '.users[0].id')
		curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/circulation/requests?query=userId=${id}"
		exit
	fi
fi

num_requests=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/circulation/requests?limit=0" |jq -r .totalRecords)

for (( offset=0; offset<=$num_requests; offset = offset + 1000 ));do
	curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/circulation/requests?query=cql.allRecords=1&limit=1000&offset=$offset" |jq -c .requests[] >> requests 
	if [[ $offset -ne 0 ]];then printf "%s records retrieved of %s\r" $offset $num_requests;fi
	done

echo 'Loans have been exported to "requests"'


