#!/usr/bin/awk -f
#

# Be sure to add a line for each date to be fixed and tweak to match format
#
# expected headers are item_barcode, patron_barcode, request_date, request_expiration_date, comment, request_type, pickup_servicepoint_id

function fixdate(value)
{
	gsub(/ .*/, "", value)
	
	if (value ~ /^[0-9]*-[0-9]*-[0-9]*$/) {
		split(value, datearr, datesep)
		retval = sprintf("%04d-%02d-%02d", datearr[3], datearr[2], datearr[1])
	} else {retval = ""}

	return retval

}

BEGIN {
	FS=OFS="\t"
	counter = 0
	datesep = "-" 
	sp["mssy"] = "e9046b79-047b-4c4e-a7a1-17d36844a127"
	sp["alby"] = "22b564d4-5cb0-4d5a-9358-f7e25e3d8fad"
	sp["well"] = "d8904061-7173-430e-b6e0-4ff37378d1ec"
	sp["extm"] = "e9046b79-047b-4c4e-a7a1-17d36844a127"
	sp["intl"] = "e9046b79-047b-4c4e-a7a1-17d36844a127"
}

{
	item_barcode=$1
	patron_barcode=$2
	request_date=$3
	request_expiration_date=$4
	comment=""
	request_type="Page"
	pickup_servicepoint_id=sp[$6]
	
	gsub("\"", "", item_barcode)
	gsub("\"", "", patron_barcode)
	gsub("\"", "", request_date)
	gsub("/", "-", request_date)
	gsub("\"", "", request_expiration_date)
	gsub("/", "-", request_expiration_date)
	gsub("\"", "", pickup_servicepoint_id)

	if (item_barcode == "") {item_barcode = item_identifier}
	if (patron_barcode == "") {patron_barcode = patron_identifier}

	gsub(/"/, "", $0)
	if (NR==1) {print "item_barcode\tpatron_barcode\trequest_date\trequest_expiration_date\tcomment\trequest_type\tpickup_servicepoint_id" > "open_requests.tsv"} else {

	counter++
	request_date = fixdate(request_date) # 
	request_expiration_date = fixdate(request_expiration_date) # 
	
	print item_barcode, patron_barcode, request_date, request_expiration_date, comment, request_type, pickup_servicepoint_id >> "open_requests.tsv" 

	if (counter % 10 == 0) {
		printf "%s records\r", counter
	}


}

}
END{ print counter" records were processed" }
