#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)
rm -f role_uuids uuids users_tmp role_users.tsv user_roles.tsv

jq -r '[.id, .name]|@tsv' roles.json > rolemap.sed
echo
echo "Retrieving user and role data"
records-get roles
echo
jq -r .id roles.json > uuids

records-getfromfile roleusers

jq -rsc '
  sort_by(.roleId)
  | group_by(.roleId)
	|.[] | [.[0].roleId, ([.[].userId]|join(","))]|@tsv' roleusers.json > role_users.tsv

jq -r .userId roleusers.json |sort -u > uuids

records-getfromfile users

jq -rsc '
  sort_by(.userId)
  | group_by(.userId)
	|.[] | [.[0].userId, ([.[].roleId]|join(","))]|@tsv' roleusers.json > user_roles.tsv

jq -r '[.id, (.username // .id)]|@tsv' users.json >> rolemap.sed

sed -i 's/^/s\//;s/\t/\//;s/$/\//' rolemap.sed

sed -f rolemap.sed role_users.tsv|sort -f > final.tsv
mv final.tsv role_users.tsv

sed -f rolemap.sed user_roles.tsv|sort -f > final.tsv
mv final.tsv user_roles.tsv
rm rolemap.sed

echo "Files listing users by role and roles by user can be found in role_users.tsv and user_roles.tsv"
echo
