#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

uuid=$(tr -dc [0-9a-f\-] <<< $1)

records-get servicepointsusers 
grep ${uuid} servicepointsusers.json > tmp

if [[ -f servicepointsusers.json ]];then
	jq -c --arg UUID "${uuid}" '.servicePointsIds |= map(select(. != $UUID)) | if .defaultServicePointId == $UUID then del(.defaultServicePointId) else . end' tmp > servicepointsusers.json 
	records-post servicepointsusers put
fi

curl -s -w '\n' -X DELETE -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/service-points/${uuid}"
