#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

if [[ ${1} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
	uuid=${1}
else
	echo "No UUID specified. Defaulting to MARC bibliographic"
	marcrules=$(curl -s -w '\n' -X GET -H "Accept: ${accept}" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/specification-storage/specifications?limit=500&query=family=MARC&profile=bibliographic&include=all")
	uuid=$(echo "${marcrules}" | jq -r '.specifications[] |select(.title == "MARC Bibliographic Specification") |.id')
fi

curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/specification-storage/specifications/${uuid}/rules" |jq -c '.rules[] |del(.metadata)' > specrules.json

echo 
echo "Output has been sent to specrules.json"
echo


