#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

uuid=${1//[^0-9a-f\-]}

apicall=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/source-storage/records/${uuid}/formatted?idType=INSTANCE") 

id=$(echo "${apicall}" |jq -r .id)
s999=$(echo "${apicall}" |jq -r '.parsedRecord.content.fields[]."999".subfields[]? | select(.s !=null) | .s')
matchedId=$(echo "${apicall}" |jq -r .matchedId)
generation=$(echo "${apicall}" |jq -r .generation)
parsedRecordId=$(echo "${apicall}" |jq -r .parsedRecord.id)
deleted=$(echo "${apicall}" |jq -r .deleted)
instanceId=$(echo "${apicall}" |jq -r .externalIdsHolder.instanceId)
i999=$(echo "${apicall}" |jq -r '.parsedRecord.content.fields[]."999".subfields[]? | select(.i !=null) | .i')
instanceHrid=$(echo "${apicall}" |jq -r .externalIdsHolder.instanceHrid)
instance001=$(echo "${apicall}" |jq -r '.parsedRecord.content.fields[] |select(."001" != null) |."001"')
state=$(echo "${apicall}" |jq -r .state)
leaderRecordStatus=$(echo "${apicall}" |jq -r .leaderRecordStatus)

echo -e "\nid                : ${id}\nmatchedId/999s    : ${matchedId} --- ${s999}\ngeneration        : ${generation}\nparsedRecordId    : ${parsedRecordId}\ndeleted           : ${deleted}\ninstanceId/999i   : ${instanceId} --- ${i999}\ninstanceHrid/001  : ${instanceHrid} --- ${instance001}\nstate             : ${state}\nleaderRecordStatus: ${leaderRecordStatus}\n"

