#!/usr/bin/bash
infile="${1}"

fileroot=$(sed 's/\.[^\.]*$//' <<< "${infile}")
outfile="${fileroot}_marc.json"

if [[ -f ${infile} ]];then echo -e "Infile could not be found";exit;fi

echo "[" > ${outfile}
pv ${infile} | jq -c 'select(.state=="ACTUAL") | .parsedRecord.content ' | sed '$!s/$/,/' >> ${outfile}
echo "]" >> ${outfile}

echo "MARC json has been extracted and exported to ${outfile}"
echo "Converting to MARC"

json2marc "${outfile}"

