#!/usr/bin/bash

if [[ ! -f ${1} ]];then
	column=${1:-1}  
	input=$(cat)
else
	input=$(cat ${1})
	column=${2:-1}
fi

echo "${input}" | awk -v col="$column" '
  {
    gsub(/[^0-9.]/, "", $col);  
    sum += $col;
  }
  END {
    print sum;
  }'

