#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

search_for=$(sed 's/[^0-9a-z\-]//gi' <<< "$1")

barcodefound=0

if [[ ${search_for} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
        endpoint="${okapi_url}/users/${search_for}"
else
	if [[ ${search_for} =~ ^[0-9a-zA-Z]+$ ]];then
        	endpoint="${okapi_url}/users?query=barcode==${search_for}"
        	barcodefound=1
	elif [[ ${search_for} =~ ^[a-z]+$ ]];then
        	endpoint="${okapi_url}/users?query=(username=%22${search_for}%2A%22%20or%20externalSystemId=%22${search_for}%2A%22)"
        	barcodefound=1
	else 
        	echo "No user was found. Exiting"
		exit
	fi
fi

apicall=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${endpoint}")

if [[ ${barcodefound} -eq 1 ]];then
	numrecords=$(echo ${apicall} |jq -r '.users |length')
	if [[ numrecords -eq 1 ]];then
        	user_uuid=$(echo ${apicall} |jq -r '.users[0].id')
        	userId=$(echo ${apicall} |jq -r '.users[0].userId')
	else 
		echo "The wrong number of records were retrieved"
	fi
else
	user_uuid=$(echo ${apicall} |jq -r '.id')
fi


curl -s -w '\n' -X DELETE -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/users/${user_uuid}"


