#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)
rm -r users.json

while read -r barcode;do
	
	query="query=barcode==${barcode}"
	
	curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/users?${query}" |jq -c . >> users.json
	
	echo "$barcode	$id" |tee -a barcode_id

done < barcodes


