#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

### adds all SPs and acq units to a user

search_for=$(sed 's/[^0-9a-z\-]//gi' <<< "$1")

barcodefound=0

if [[ ${search_for} =~ ^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*$ ]];then
        endpoint="${okapi_url}/users/${search_for}"
	userId=${search_for}
else
	if [[ ${search_for} =~ ^[0-9]+$ ]];then
        	endpoint="${okapi_url}/users?query=barcode==${search_for}"
        	barcodefound=1
	elif [[ ${search_for} =~ ^[a-zA-Z]+$ ]];then
        	endpoint="${okapi_url}/users?query=(username=%22${search_for}%2A%22%20or%20externalSystemId=%22${search_for}%2A%22)"
        	barcodefound=1
	else 
		if [[ -z $1 ]];then
			curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/users?limit=0"
		else
        		echo "No user was found. Exiting"
		fi
		exit
	fi
fi

apicall=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${endpoint}")

if [[ ${barcodefound} -eq 1 ]];then
	numrecords=$(echo ${apicall} |jq -r '.users |length')
	if [[ numrecords -eq 1 ]];then
        	userId=$(echo $apicall |jq -r '.users[0].id')
	else 
		echo "$numrecords retrieved. Must retrieve only on record. Exiting"
	fi
fi

acqunit_arr=($(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/acquisitions-units/units?limit=1000" |jq -r '.acquisitionsUnits[].id'))

servicepoint_arr=($(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/service-points" |jq -r '.servicepoints[].id'))

servicePointIds=$(echo -n "${servicepoint_arr[@]}" | jq -Rs 'split(" ") ')

echo "Adding service points"

servicePointUserId=$(curl -s -w '\n' -X GET -D -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/service-points-users?query=userId==${userId}" |jq -r '.servicePointsUsers[0].id')

if [[ $servicePointUserId == null ]];then 
	servicePointUserId=$(uuidgen)
	postdata="{ \"id\": \"${servicePointUserId}\", \"userId\":\"${userId}\", \"servicePointsIds\": ${servicePointIds} }"

	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${postdata}" "${okapi_url}/service-points-users"
else
	postdata="{ \"id\": \"${servicePointUserId}\", \"userId\":\"${userId}\", \"servicePointsIds\": ${servicePointIds} }"
	curl --http1.1 -s -w '\n' -X PUT -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${postdata}" "${okapi_url}/service-points-users/${servicePointUserId}"
fi



echo "Adding acq units"

for acqUnitId in "${acqunit_arr[@]}";do
	postdata="{\"userId\":\"${userId}\",\"acquisitionsUnitId\":\"${acqUnitId}\"}"

	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${postdata}" "${okapi_url}/acquisitions-units/memberships"
done

