#!/usr/bin/bash
auth 2>/dev/null || authn 2>/dev/null
tenant=$(cat tenant)
okapi_url=$(cat okapi.url)
okapi_token=$(cat okapi.token)

search="${1,,}"
limit=5000

if [[ ${search} == "" ]];then echo "You must supply some input";exit;fi

function showmatches() {

	local matchtype="${1}"
	local endpoint
	local jq

	jq=".${matchtype}[] | select((.name |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .name] |@tsv"

	case $matchtype in
	"acquisitionMethods")
		jq=".${matchtype}[] | select((.value |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .value] |@tsv"
		endpoint="orders/acquisition-methods";;
	"acquisitionsUnits")
		endpoint="acquisitions-units/units";;
	"authoritySourceFiles")
		limit=50
		endpoint="authority-source-files";;
	"addressTypes")
		endpoint="addresstypes"
		jq=".${matchtype}[] | select((.addressType  |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .addressType ] |@tsv";;
	"cancellationReasons")
		endpoint="cancellation-reason-storage/cancellation-reasons";;
	"callNumberTypes")
		endpoint="call-number-types";;
	"categories")
		endpoint="organizations-storage/categories"
		jq=".${matchtype}[] | select((.value |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .value] |@tsv";;
	"contributorTypes")
		endpoint="contributor-types"
		jq="code_name";;
	"courseDepartments")
		endpoint="coursereserves/departments"
		jq=".departments[] | select((.name |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"courseDepartments\", .id, .name] |@tsv";;
	"courseTerms")
		endpoint="coursereserves/terms"
		jq=".terms[] | select((.name |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"courseTerms\", .id, .name] |@tsv";;
	"courseTypes")
		endpoint="coursereserves/coursetypes";;
	"departments")
		endpoint="departments"
		jq="code_name";;
	"expenseClasses")
		endpoint="finance/expense-classes"
		jq="code_name";;
	"feefineowners")
		endpoint="owners"
		jq=".owners[] | select((.owner  |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"feefineowners\", .id, .owner] |@tsv";;
	"fiscalYears")
		endpoint="finance/fiscal-years"
		jq="code_name";;
	"finance-groups")
		endpoint="finance/groups"
		jq=".groups[] | select((.name |ascii_downcase |contains(\"${search}\"))  or (.code | ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"finance-groups\", .id, .code,.name] |@tsv";;
	"funds")
		endpoint="finance/funds"
		jq="code_name";;
	"fundTypes")
		endpoint="finance/fund-types";;
	"holdingsRecordsSources")
		endpoint="holdings-sources";;
	"holdingsTypes")
		endpoint="holdings-types";;
	"identifierTypes")
		endpoint="identifier-types";;
	"instanceFormats")
		endpoint="instance-formats";;
	"instanceRelationshipTypes")
		endpoint="instance-relationship-types";;
	"instanceNoteTypes")
		endpoint="instance-note-types";;
	"instanceStatuses")
		endpoint="instance-statuses";;
	"instanceTypes")
		endpoint="instance-types";;
	"holdingsNoteTypes")
		endpoint="holdings-note-types";;
	"itemDamageStatuses")
		endpoint="item-damaged-statuses";;
	"itemNoteTypes")
		endpoint="item-note-types";;
	"ledgers")
		endpoint="finance/ledgers"
		jq="code_name";;
	"loanPolicies")
		endpoint="loan-policy-storage/loan-policies";;
	"loantypes")
		endpoint="loan-types";;
	"locations")
		endpoint="locations"
		jq="code_name";;
	"loccamps")
		endpoint="location-units/campuses"
		jq="code_name";;
	"locinsts")
		endpoint="location-units/institutions"
		jq="code_name";;
	"loclibs")
		endpoint="location-units/libraries"
		jq="code_name";;
	"lostItemFeePolicies")
		endpoint="lost-item-fees-policies";;
	"mtypes")
		endpoint="material-types";;
	"noteTypes")
		endpoint="note-types";;
	"organizationTypes")
		endpoint="organizations-storage/organization-types";;
	"overdueFinePolicies")
		endpoint="overdue-fines-policies";;
	"patronNoticePolicies")
		endpoint="patron-notice-policy-storage/patron-notice-policies";;
	"requestPolicies")
		endpoint="request-policy-storage/request-policies";;
	"servicepoints")
		endpoint="service-points"
		jq="code_name";;
	"statisticalCodes")
		endpoint="statistical-codes"
		jq="code_name";;
	"statisticalCodeTypes")
		endpoint="statistical-code-types";;
	"usergroups")
		endpoint="groups"
		jq=".${matchtype}[] | select((.group  |ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .group] |@tsv";;
	*)
		echo "No matching endpoint could be found. Quitting"
		exit	;;
	esac

	if [[ ${jq} == "code_name" ]];then 
		jq=".${matchtype}[] | select((.name |ascii_downcase |contains(\"${search}\"))  or (.code | ascii_downcase |contains(\"${search}\")) or (.id == \"${search}\")) | [\"${matchtype}\", .id, .code,.name] |@tsv"
	fi
		

	output=$(curl -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/${endpoint}?query=cql.allRecords=1&limit=${limit}" \
		|jq -r "${jq}") 
		echo -e "${output}" |grep [a-z] && echo


}


echo "Downloading data for  acq methods, acq units, address types, authority source files, call number types, cancellation reasons, categories, contributor types, course departments, course types, courses, expense classes, fee/fine owners, fiscal years, finance-groups, funds, fundtypes, holdings note types, holdings record sources, holdings types, identifier types, instance formats, instance note types, instance relationship types, instance statuses, instance types, item damaged statuses, item material types, item note types, ledgers, loan policies, loan types, locations, location institutions, location campuses, location libraries, lost item fee policies, note types, organization types, overdue fine policies, patron notice policies, request policies, service points, statcodes, statcodetypes, and usergroups"

rec_array=("acquisitionMethods acquisitionsUnits" "addressTypes" "authoritySourceFiles" "callNumberTypes" "cancellationReasons" "categories" "contributorTypes" "courseDepartments" "courseTerms" "courseTypes" "departments" "expenseClasses" "feefineowners" "fiscalYears" "finance-groups" "funds" "fundTypes" "holdingsNoteTypes" "holdingsRecordsSources" "holdingsTypes" "identifierTypes" "instanceFormats" "instanceNoteTypes" "instanceRelationshipTypes" "instanceStatuses" "instanceTypes" "itemDamageStatuses" "itemNoteTypes" "ledgers" "loanPolicies" "loantypes" "locations" "locinsts" "loccamps" "loclibs" "lostItemFeePolicies" "mtypes" "noteTypes" "organizationTypes" "overdueFinePolicies" "patronNoticePolicies" "requestPolicies" "servicepoints" "statisticalCodes" "statisticalCodeTypes" "usergroups")

counter=1
for rec_type in "${rec_array[@]}";do
	showmatches ${rec_type} &
	if [[ $(($counter % 10)) -eq 0 ]];then wait;fi
	counter=$(($counter + 1))
done

wait


