#!/usr/bin/bash

if [[ ! -f "${1}" ]] || [[ -z "${2}" ]];then
	echo 
	echo "You must specify a tab delimited source file and a regex"
	echo 
	echo "Usage: whichfield [sourcefile] [regex]"
	echo
	exit
fi

pv "${1}" | awk -v REGEX="${2}" 'BEGIN{print "Record\tField\tValue"}{
  for (i = 1; i <= NF; i++)
    if ($i ~ REGEX)
      printf("%d\t%d\t%s\n", FNR, i, $i)
}' > whichfield.tsv

echo "The record and field numbers as well as matched entries have been output to whichfield.tsv" 
