#!/usr/bin/bash

if [[ ! "${1}" ]];then
	echo 
	echo "You must specify a tab delimited source file and a regex"
	echo 
	echo "Usage: whichfield [sourcefile] [regex]"
	echo
	exit 1
fi

if [[ ! -f "${1}" ]];then
	regex="${1}"

	awk -v REGEX="${regex}" 'BEGIN{print "Record\tField\tValue"}{
	  for (i = 1; i <= NF; i++)
	    if ($i ~ REGEX)
	      printf("%d\t%d\t%s\n", FNR, i, $i)
	}' 
else
	regex="${2}"
	sourcefile="${1}"

	pv "${sourcefile}" | awk -v REGEX="${regex}" 'BEGIN{print "Record\tField\tValue"}{
	  for (i = 1; i <= NF; i++)
	    if ($i ~ REGEX)
	      printf("%d\t%d\t%s\n", FNR, i, $i)
	}' > whichfield.tsv
	
	echo "The record and field numbers as well as matched entries have been output to whichfield.tsv" 
fi

